
== REST API

=== Activiti REST一般原则 General Activiti REST principles

==== 安装与认证 Installation and Authentication

Activiti在引擎中包含了REST API，可以通过在servlet容器如Apache Tomcat中，部署activiti-rest.war文件来安装。但是，也可以在其他的web应用中使用，只要在你的应用中包含这些servlet与其映射，并在classpath中添加所有activiti-rest依赖。

默认情况下Activiti引擎链接至一个H2内存数据库。可以修改WEB-INF/classes文件夹下的db.properties文件中的数据库设置。REST API使用JSON格式（http://www.json.org），基于Spring MVC（http://docs.spring.io/spring/docs/current/spring-framework-reference/html/mvc.html）构建。

默认情况下，所有REST资源都需要有一个合法的Activiti已认证用户，使用基础HTTP访问认证，因此在请求时，可以在HTTP头添加++Authorization: Basic ...==++，或者在请求url中包含用户名与密码（例如++http://username:password@localhost...++）。

**建议使用基础认证时同时使用HTTPS。**

==== 配置 Configuration

Activiti REST web应用使用Spring Java Configuration来启动Activiti引擎，定义基础认证安全使用Spring security，以及为特定的变量处理定义变量转换。可以修改WEB-INF/classes目录下的engine.properties文件，进行少量参数的定义。如果需要高级配置选项，可以在activiti-custom-context.xml文件中覆盖默认的Spring bean，这个文件也在WEB-INF/classes目录下。该文件中已经以注释形式提供了示例配置。也可以在这里通过定义一个新的命名为restResponsefactory的Spring bean，覆盖默认的RestResponseFactory，并使用自定义实现类。

[[restUsageInTomcat]]


==== 在Tomcat中使用 Usage in Tomcat

由于link:$$http://tomcat.apache.org/tomcat-7.0-doc/security-howto.html$$[Tomcat中的默认安全参数]，**默认不能使用转义斜线（++%2F++与++%5C++）（返回400结果）。**这可能会影响部署资源与其数据URL，因为URL可能隐含转义斜线。

**当发现非预期的400结果时，设置下列系统参数 +$$-Dorg.apache.tomcat.util.buf.UDecoder.ALLOW_ENCODED_SLASH=true.$$+ **

最佳实践是（post/put JSON时），在下面描述的HTTP请求中，永远将**Accept**与**Content-Type**头设置为**application/json**。


==== 方法与返回码 Methods and return-codes

.HTTP方法与相应操作
[options="header"]
|===============
|方法|操作
|+GET+|获取单个资源，或获取一组资源。
|+POST+|创建一个新资源。在查询结构太复杂，不能放入GET请求的查询URL中时，也用于执行资源查询。
|+PUT+|更新一个已有资源的参数。也用于在已有资源上的调用动作。
|+DELETE+|删除一个已有资源。。

|===============


.HTTP方法响应码
[options="header"]
|===============
|响应|描述
|+200 - Ok+|操作成功，返回响应（++GET++与++PUT++请求）。
|++201 - 已创建++|操作成功，已经创建了实体，并在响应体中返回（++POST++请求）。
|++204 - 无内容++|操作成功，已经删除了实体，因此没有返回的响应体（++DELETE++请求）。
|++401 - 未认证++|操作失败。操作要求设置认证头。如果请求中有认证头，则提供的鉴证并不合法，或者用户未被认证进行该操作。
|++403 - 禁止++|操作被禁止，且不应重试。这不是鉴证或授权的问题，而是说明不允许该操作。例如：删除一个运行中流程的任务是且永远是不允许的，无论该用户或流程/任务的状态。
|++404 - 未找到++|操作失败。请求的资源未找到。
|++405 - 不允许的方法++|操作失败。使用的方法不能用于该资源。例如，更新（PUT）部署资源将导致++405++状态。
|++409 - 冲突++|操作失败。该操作导致更新一个已被其他操作更新的资源，因此本更新不再有效。也可以表明正在为一个集合创建一个资源，但该集合中已经使用了该标识符。
|++415 - 不支持的媒体类型++|操作失败。请求提包含了不支持的媒体类型。也会发生在请求体JSON中包含了未知的属性或值，但没有正确的格式/类型来接受。
|++500 - 服务器内部错误++|操作失败。执行操作时发生了未知异常。响应体中包含了错误的细节。

|===============

HTTP响应的media-type总是++application/json++，除非请求二进制内容（例如部署资源数据），这时将使用media-type的内容。

==== 错误响应体 Error response body

当发生错误时（客户端与服务器端都可能，4XX及5XX状态码），响应体会包含一个描述了发生的错误的对象。任务未找到时的404状态的例子：

[source,json,linenums]
----
{
  "statusCode" : 404,
  "errorMessage" : "Could not find a task with id '444'."
}
----


==== 请求参数 Request parameters

===== URL片段 URL fragments

作为url的一部分的参数（例如，++http://host/actviti-rest/service/repository/deployments/{deploymentId}++中的deploymentId参数），如果包含特殊字符，则需要进行合适的转义（参见link:$$https://en.wikipedia.org/wiki/Percent-encoding$$[URL编码或百分号编码]）。大多数框架都内建了这个功能，但要记得考虑它。特别是对可能包含斜线符的段落（例如部署资源），就是必须的。

===== Rest URL查询参数 Rest URL query parameters

作为查询字符串添加在URL中的参数（例如++http://host/activiti-rest/service/deployments?name=Deployment++中的name参数）可以使用下列类型，也会在相应的REST-API文档中提到：

.URL查询参数类型
[options="header"]
|===============
|类型|格式
|String|纯文本参数。可以包含任何URL允许的合法字符。对于++XXXLike+ +参数，字符串可能会包含通配符++%++（需要进行URL编码）。可以进行like搜索。例如，'++Tas%++'将匹配所有以'Tas'开头的值。
|Integer|整形参数。只能包含数字型非十进制值（原文如此，下同），在-2.147.483.648至2.147.483.647之间。
|Long|长整形参数。只能包含数字型非十进制值，在-9.223.372.036.854.775.808至9.223.372.036.854.775.807之间。
|Boolean|boolean型参数。可以为++true++或++false++。任何其他值都会导致'++405 - 错误请求++'响应。
|Date|日期型参数。使用ISO-8601日期格式（参考link:$$http://en.wikipedia.org/wiki/ISO_8601$$[wikipedia中的ISO-8601]），使用时间与日期组分（例如++2013-04-03T23:45Z++）。

|===============


[[restJsonBody]]


===== JSON体参数 JSON body parameters

.JSON参数类型
[options="header"]
|===============
|类型|格式
|String|纯文本参数。对于++XXXLike+ +参数，字符串可能会包含通配符++%++。可以进行like搜索。例如，'++Tas%++'将匹配所有以'Tas'开头的值。
|Integer|整形参数，使用JSON数字。只能包含数字型非十进制值（原文如此，下同），在-2.147.483.648至2.147.483.647之间。
|Long|长整形参数，使用JSON数字。只能包含数字型非十进制值，在-9.223.372.036.854.775.808至9.223.372.036.854.775.807之间。
|Date|日期型参数，使用JSON文本。使用ISO-8601日期格式（参考link:$$http://en.wikipedia.org/wiki/ISO_8601$$[wikipedia中的ISO-8601]），使用时间与日期组分（例如++2013-04-03T23:45Z++）。

|===============


[[restPagingAndSort]]


===== 分页与排序 Paging and sorting

分页与排序参数可以作为查询字符串加入URL中（例如++http://host/activiti-rest/service/deployments?sort=name++中的name参数）。

.查询变量参数
[options="header"]
|===============
|参数|默认值|描述
|sort|各查询实现不同|排序键的名字，在各查询实现中默认值与可用值都不同。
|order|asc|排序顺序，可以是'asc'（顺序）或'desc'（逆序）。
|start|0|对结果分页的参数。默认结果从0开始。
|size|10|对结果分页的参数。默认大小为10.

|===============


[[restQueryVariable]]


===== JSON查询变量格式

[source,json,linenums]
----

{
  "name" : "variableName",
  "value" : "variableValue",
  "operation" : "equals",
  "type" : "string"
}
----


.JSON查询变量参数
[options="header"]
|===============
|参数|必填|描述
|name|否|包含在查询中的变量名。在有些使用'++equals++'查询中可以为空，查询**任意变量名**具有给定值的资源。
|value|是|包含在查询中的变量值，需要使用给定类型的正确格式。
|operator|是|查询使用的操作，可以为下列值：++equals、notEquals、equalsIgnoreCase、notEqualsIgnoreCase、lessThan、greaterThan、lessThanOrEquals、greaterThanOrEquals++与++like++。
|type|否|所用变量的类型。当省略时，会从++value++参数推理类型。任何JSON文本值都认为是++string++类型，JSON boolean值认为是++boolean++类型，JSON数字认为是++long++或++integer++，取决于数字的大小。建议在有疑惑时显示指定类型。其他支持的类型列在下面。


|===============


.默认查询JSON类型
[options="header"]
|===============
|类型名|描述
|string|值处理转换为++java.lang.String++。
|short|值处理转换为++java.lang.Integer++。
|integer|值处理转换为++java.lang.Integer++。
|long|值处理转换为++java.lang.Long++。
|double|值处理转换为++java.lang.Double++。
|boolean|值处理转换为++java.lang.Boolean++。
|date|值处理转换为++java.util.Date++。JSON字符串将使用ISO-8601日期格式转换。

|===============


[[restVariables]]

===== 变量表示 Variable representation

当使用变量时（执行/流程与任务），读取与写入时REST-api都使用一些通用原则与JSON格式。变量的JSON表示像是这样：

[source,json,linenums]
----
{
  "name" : "variableName",
  "value" : "variableValue",
  "valueUrl" : "http://...",
  "scope" : "local",
  "type" : "string"
}
----

.变量的JSON属性
[options="header"]
|===============
|参数|必填|描述
|name|是|变量名。
|value|否|变量的值。当写入变量且省略了++value++时，会使用++null++作为值。
|valueUrl|否|当读取++binary++或++serializable++类型的变量时，这个属性将指向可用于获取原始二进制数据的URL。
|scope|否|变量的范围。如果值为'++local++'，则变量显式定义在其请求的资源上。如果值为'++global++'，则变量定义在其父上（或者父树中的任意父）。当写入变量且省略了scope时，使用++global++。
|type|否|变量的类型。查看下面的表格了解类型的更多信息。当写入变量且省略了这个值时，将使用请求的原始JSON属性类型推断，限制在++string++、++double++、++integer++与++boolean++中。建议总是包含类型，以确保不会错误推断类型。
|===============


.变量类型
[options="header"]
|===============
|类型名|描述
|string|值按照++java.lang.String++处理。写入变量时使用原始JSON文本。
|integer|值按照++java.lang.Integer++处理。按约定写入变量时使用JSON数字，失败则退回JSON文本。
|short|值按照++java.lang.Short++处理。按约定写入变量时使用JSON数字，失败则退回JSON文本。
|long|
|short|值按照++java.lang.Long++处理。按约定写入变量时使用JSON数字，失败则退回JSON文本。
|double|值按照++java.lang.Double++处理。按约定写入变量时使用JSON数字，失败则退回JSON文本。
|boolean|值按照++java.lang.Boolean++处理。按约定写入变量时使用JSON boolean。
|date|值按照++java.util.Date++处理。写入变量时将转换为ISO-8601日期格式。
|binary|二进制变量，按照字节数组处理。++value++属性为null，++valueUrl++包含指向原始二进制流的URL。
|serializable|代表序列化的Java对象。与++binary++类型一样，++value++属性为null，++valueUrl++包含指向原始二进制流的URL。所有可序列化的变量（不是上述任意类型的）将被暴露为这个类型的变量。
|===============

可以使用自定义JSON表示，支持额外的变量类型（既可以是简单值，也可以是复杂/嵌套的JSON对象）。通过扩展++org.activiti.rest.service.api.RestResponseFactory++的++initializeVariableConverters()++方法，可以添加额外的++org.activiti.rest.service.api.engine.variable.RestVariableConverter++类，来将你的POJO转换为适合通过REST传输的格式，以及将REST值转换为POJO。实际转换JSON使用Jackson。


=== 部署 Deployment

**使用tomcat时，请阅读<<restUsageInTomcat,在Tomcat中使用>>。**

==== 部署的列表 List of Deployments

----
GET repository/deployments
----

.URL查询参数
[options="header"]
|===============
|参数|必填|值|描述
|name|否|String|只返回给定名字的部署。
|nameLike|否|String|只返回名字like给定名字的部署。
|category|否|String|只返回给定分类的部署。
|categoryNotEquals|否|String|只返回不是给定分类的部署。
|tenantId|否|String|只返回给定tenantId的部署。
|tenantIdLike|否|String|只返回tenantId like给定值的部署。
|withoutTenantId|否|Boolean|如果值为++true++，只会返回没有设置tenantId的部署。如果值为++false++，则忽略++withoutTenantId++参数。
|sort|否|'id'（默认）、'name'、'deploytime'或'tenantId'|用于排序的参数，与'order'一起使用。

|===============

可以在这个URL中使用通用<<restPagingAndSort,分页与排序查询参数>>。

.REST返回码
[options="header"]
|===============
|返回码|描述
|200|代表请求成功。

|===============

**成功响应体：**

[source,json,linenums]
----
{
  "data": [
    {
      "id": "10",
      "name": "activiti-examples.bar",
      "deploymentTime": "2010-10-13T14:54:26.750+02:00",
      "category": "examples",
      "url": "http://localhost:8081/service/repository/deployments/10",
      "tenantId": null
    }
  ],
  "total": 1,
  "start": 0,
  "sort": "id",
  "order": "asc",
  "size": 1
}
----

==== 获取一个部署 Get a deployment

----
GET repository/deployments/{deploymentId}
----

.获取一个部署 - URL参数
[options="header"]
|===============
|参数|必填|值|描述
|deploymentId|是|String|要获取的部署的id。

|===============


.获取一个部署 - 响应码
[options="header"]
|===============
|响应码|描述
|200|代表已找到并返回部署。
|404|代表未找到请求的部署。

|===============

**成功响应体：**

[source,json,linenums]
----
{
  "id": "10",
  "name": "activiti-examples.bar",
  "deploymentTime": "2010-10-13T14:54:26.750+02:00",
  "category": "examples",
  "url": "http://localhost:8081/service/repository/deployments/10",
  "tenantId" : null
}
----

==== 创建一个新部署 Create a new deployment

----
POST repository/deployments
----

**请求体：**

请求体需要包含__multipart/form-data__类型的数据。请求中需要只有一个文件，额外文件将被忽略。部署名是传入的文件字段的名字。如果要在一个部署中部署多个资源，需要将资源压缩为zip文件，并确保文件名以++.bar++或++.zip++结尾。

可以在请求体中传递名为++tenantId++的额外参数（表单字段）。这个字段的值将用作部署所在的租户（tenant）的id。

.创建一个新部署 - 响应码
[options="header"]
|===============
|响应码|描述
|201|代表成功创建部署
|400|代表请求体中没有内容，或部署不支持内容的mime-type。状态描述中包含了额外信息。

|===============

**成功响应体：**


[source,json,linenums]
----
{
  "id": "10",
  "name": "activiti-examples.bar",
  "deploymentTime": "2010-10-13T14:54:26.750+02:00",
  "category": null,
  "url": "http://localhost:8081/service/repository/deployments/10",
  "tenantId" : "myTenant"
}
----

==== 删除一个部署 Delete a deployment

----
DELETE repository/deployments/{deploymentId}
----

.删除一个部署 - URL参数
[options="header"]
|===============
|参数|必填|值|描述
|deploymentId|是|String|要删除的部署的id。

|===============


.删除一个部署 - 响应码
[options="header"]
|===============
|响应码|描述
|204|代表已找到并删除了部署。响应体设置为空。
|404|代表未找到请求的部署。

|===============


==== 列表部署中的资源 List resources in a deployment

----
GET repository/deployments/{deploymentId}/resources
----

.列表部署中的资源 - URL参数
[options="header"]
|===============
|参数|必填|值|描述
|deploymentId|是|String|要获取资源的部署的id。

|===============

.列表部署中的资源 - 响应码
[options="header"]
|===============
|响应码|描述
|200|代表已找到部署，并返回了资源的列表。
|404|代表未找到请求的部署。

|===============

**成功响应体：**

[source,json,linenums]
----
[
  {
    "id": "diagrams/my-process.bpmn20.xml",
    "url": "http://localhost:8081/activiti-rest/service/repository/deployments/10/resources/diagrams%2Fmy-process.bpmn20.xml",
    "dataUrl": "http://localhost:8081/activiti-rest/service/repository/deployments/10/resourcedata/diagrams%2Fmy-process.bpmn20.xml",
    "mediaType": "text/xml",
    "type": "processDefinition"
  },
  {
    "id": "image.png",
    "url": "http://localhost:8081/activiti-rest/service/repository/deployments/10/resources/image.png",
    "dataUrl": "http://localhost:8081/activiti-rest/service/repository/deployments/10/resourcedata/image.png",
    "mediaType": "image/png",
    "type": "resource"
  }
]
----


* ++mediaType++: 包含了资源的媒体类型。使用（可插入的）++MediaTypeResolver++解析，默认包含有限数量的媒体类型映射。
* ++type++: 资源的类型，可用值为：（原文空缺）
* ++resource++: 简单老式资源。
* ++processDefinition++: 包含一个或多个流程定义的资源。通过部署器挑选。
* ++processImage++: 代表流程定义的图形化输出的资源。

__结果JSON中单个资源的dataUrl参数包含了获取该二进制资源的实际URL。__


==== 获取一个部署资源 Get a deployment resource

----
GET repository/deployments/{deploymentId}/resources/{resourceId}
----

.获取一个部署资源 - URL 参数
[options="header"]
|===============
|参数|必填|值|描述
|deploymentId|是|String|请求的资源所在的部署的id。
|resourceId|是|String|要获取的资源的id。**请确保如果包含斜线符，需要对resourceId进行URL编码。例如，使用'diagrams%2Fmy-process.bpmn20.xml'代替'diagrams/Fmy-process.bpmn20.xml'。**

|===============


.获取一个部署资源 - 响应码
[options="header"]
|===============
|响应码|描述
|200|代表找到了部署与资源，并返回了资源。
|404|代表未找到请求的部署，或者该部署中没有给定id的资源。状态描述包含了额外信息。

|===============


**成功响应体：**

[source,json,linenums]
----
{
  "id": "diagrams/my-process.bpmn20.xml",
  "url": "http://localhost:8081/activiti-rest/service/repository/deployments/10/resources/diagrams%2Fmy-process.bpmn20.xml",
  "dataUrl": "http://localhost:8081/activiti-rest/service/repository/deployments/10/resourcedata/diagrams%2Fmy-process.bpmn20.xml",
  "mediaType": "text/xml",
  "type": "processDefinition"
}
----


* ++mediaType++: 包含了资源的媒体类型。使用（可插入的）++MediaTypeResolver++解析，默认包含有限数量的媒体类型映射。
* ++type++: 资源的类型，可用值为：（原文空缺）
* ++resource++: 简单老式资源。
* ++processDefinition++: 包含一个或多个流程定义的资源。通过部署器挑选。
* ++processImage++: 代表流程定义的图形化输出的资源。


==== 获取一个部署资源的内容 Get a deployment resource content

----
GET repository/deployments/{deploymentId}/resourcedata/{resourceId}
----

.获取一个部署资源的内容 - URL 参数
[options="header"]
|===============
|参数|必填|值|描述
|deploymentId|是|String|请求的资源所在的部署的id。
|resourceId|是|String|要获取的资源的id。**请确保如果包含斜线符，需要对resourceId进行URL编码。例如，使用'diagrams%2Fmy-process.bpmn20.xml'代替'diagrams/Fmy-process.bpmn20.xml'。**

|===============



.获取一个部署资源的内容 - 响应码
[options="header"]
|===============
|响应码|描述
|200|代表找到了部署与资源，并返回了资源。
|404|代表未找到请求的部署，或者该部署中没有给定id的资源。状态描述包含了额外信息。

|===============

**成功响应体：**

响应体将包含所请求资源的二进制资源内容。响应的content-type与资源'mimeType'参数返回的类型相同。同时，设置content-disposition头，让浏览器可以下载文件而不是直接显示。


=== 流程定义 Process Definitions


==== 列表流程定义 List of process definitions


----
GET repository/process-definitions
----

.List of process definitions - URL 参数
[options="header"]
|===============
|参数|必填|值|描述
|version|否|integer|只返回给定版本的流程定义。
|name|否|String|只返回给定名字的流程定义。
|nameLike|否|String|只返回名字like给定名字的流程定义。
|key|否|String|只返回给定key的流程定义。
|keyLike|否|String|只返回key like给定key的流程定义。
|resourceName|否|String|只返回给定资源名的流程定义。
|resourceNameLike|否|String|只返回资源名like给定资源名的流程定义。
|category|否|String|只返回给定分类的流程定义
|categoryLike|否|String|只返回分类名like给定名字的流程定义。
|categoryNotEquals|否|String|只返回不是给定分类的流程定义。
|deploymentId|否|String|只返回给定id的部署中的流程定义。
|startableByUser|否|String|只返回给定用户可以启动的流程定义。
|latest|否|Boolean|只返回流程定义的最新版本。只能与'key'及'keyLike'参数一起使用，使用任何其它参数都将导致400响应。
|suspended|否|Boolean|如果值为++true++，则只返回暂停的流程定义。如果为值为++false++，则只返回活动的流程定义（未挂起的）。
|sort|否|'name'（默认）、'id'、'key'、'category'、'deploymentId'与'version'|用于排序的参数，与'order'一起使用。

|===============

可以在这个URL中使用通用<<restPagingAndSort,分页与排序查询参数>>。

.List of process definitions - 响应码
[options="header"]
|===============
|响应码|描述
|200|代表请求成功，返回了流程定义。
|400|代表某个参数格式错误，或者'latest'与'key'、'keyLike'以外的其他参数一起使用。状态描述中包含了额外信息。

|===============


**成功响应体：**

[source,json,linenums]
----
{
  "data": [
    {
      "id" : "oneTaskProcess:1:4",
      "url" : "http://localhost:8182/repository/process-definitions/oneTaskProcess%3A1%3A4",
      "version" : 1,
      "key" : "oneTaskProcess",
      "category" : "Examples",
      "suspended" : false,
      "name" : "The One Task Process",
      "description" : "This is a process for testing purposes",
      "deploymentId" : "2",
      "deploymentUrl" : "http://localhost:8081/repository/deployments/2",
      "graphicalNotationDefined" : true,
      "resource" : "http://localhost:8182/repository/deployments/2/resources/testProcess.xml",
      "diagramResource" : "http://localhost:8182/repository/deployments/2/resources/testProcess.png",
      "startFormDefined" : false
    }
  ],
  "total": 1,
  "start": 0,
  "sort": "name",
  "order": "asc",
  "size": 1
}
----


* ++graphicalNotationDefined++: 代表包含有图形信息（BPMN DI）的流程定义。
* ++resource++: 包含实际部署的BPMN 2.0 XML。
* ++diagramResource++: 包含流程的图形化表示。如果没有可用流程图则为null。


==== 获取一个流程定义

----
GET repository/process-definitions/{processDefinitionId}
----

.获取一个流程定义 - URL 参数
[options="header"]
|===============
|参数|必填|值|描述
|processDefinitionId|是|String|要获取的流程定义的id。

|===============


.获取一个流程定义 - 响应码
[options="header"]
|===============
|响应码|描述
|200|代表找到并返回了流程定义。
|404|代表未找到请求的流程定义。

|===============


**成功响应体：**

[source,json,linenums]
----
{
  "id" : "oneTaskProcess:1:4",
  "url" : "http://localhost:8182/repository/process-definitions/oneTaskProcess%3A1%3A4",
  "version" : 1,
  "key" : "oneTaskProcess",
  "category" : "Examples",
  "suspended" : false,
  "name" : "The One Task Process",
  "description" : "This is a process for testing purposes",
  "deploymentId" : "2",
  "deploymentUrl" : "http://localhost:8081/repository/deployments/2",
  "graphicalNotationDefined" : true,
  "resource" : "http://localhost:8182/repository/deployments/2/resources/testProcess.xml",
  "diagramResource" : "http://localhost:8182/repository/deployments/2/resources/testProcess.png",
  "startFormDefined" : false
}
----

* ++graphicalNotationDefined++: 代表包含有图形信息（BPMN DI）的流程定义。
* ++resource++: 包含实际部署的BPMN 2.0 XML。
* ++diagramResource++: 包含流程的图形化表示。如果没有可用流程图则为null。


==== 更新流程定义的分类 Update category for a process definition

----
PUT repository/process-definitions/{processDefinitionId}
----


**JSON体：**

[source,json,linenums]
----
{
  "category" : "updatedcategory"
}
----


.更新流程定义的分类 - 响应码
[options="header"]
|===============
|响应码|描述
|200|代表流程的分类已经修改。
|400|代表请求体中未定义分类。
|404|代表未找到请求的流程定义。

|===============


**成功响应体：**参见++repository/process-definitions/{processDefinitionId}++的响应。


==== 获取一个流程定义资源的内容 Get a process definition resource content

----
GET repository/process-definitions/{processDefinitionId}/resourcedata
----

.获取一个流程定义资源的内容 - URL 参数
[options="header"]
|===============
|参数|必填|值|描述
|processDefinitionId|是|String|The id of the process definition to get the resource data for.

|===============

**响应：**

与++GET repository/deployment/{deploymentId}/resourcedata/{resourceId}++完全一样的响应码/响应体。


==== 获取一个流程定义的BPMN模型 Get a process definition BPMN model

----
GET repository/process-definitions/{processDefinitionId}/model
----

.获取一个流程定义的BPMN模型 - URL 参数
[options="header"]
|===============
|参数|必填|值|描述
|processDefinitionId|是|String|要获取模型的流程定义的id。

|===============


.获取一个流程定义的BPMN模型 - 响应码
[options="header"]
|===============
|响应码|描述
|200|代表已找到流程定义，并返回了模型。
|404|代表未找到请求的流程定义。

|===============


**响应体：**响应体是一个代表了++org.activiti.bpmn.model.BpmnModel++的JSON，包含所有流程定义模型。

[source,json,linenums]
----
{
   "processes":[
      {
         "id":"oneTaskProcess",
         "xmlRowNumber":7,
         "xmlColumnNumber":60,
         "extensionElements":{

         },
         "name":"The One Task Process",
         "executable":true,
         "documentation":"One task process description",

    ]
}
----


==== 暂停一个流程定义 Suspend a process definition


----
PUT repository/process-definitions/{processDefinitionId}
----

**JSON体：**

[source,json,linenums]
----
{
  "action" : "suspend",
  "includeProcessInstances" : "false",
  "date" : "2013-04-15T00:42:12Z"
}
----


[[processDefinitionActionBodyParameters]]
.暂停一个流程定义 - JSON体参数
[options="header"]
|===============
|参数|描述|必填
|action|要进行的操作，++activate++或++suspend++。|是
|includeProcessInstances|是否同时暂停/激活该流程定义的运行中流程实例。如果省略，则流程实例保持原有状态。|否
|date|要进行暂停/激活操作的日期（ISO-8601）。如果省略，则暂停/激活立刻生效。|否

|===============


.暂停一个流程定义 - 响应码
[options="header"]
|===============
|响应码|描述
|200|代表已暂停流程。
|404|代表未找到请求的流程定义。
|409|代表请求的流程定义之前已经暂停。

|===============

**成功响应体：**参见++repository/process-definitions/{processDefinitionId}++的响应

==== 激活一个流程定义 Activate a process definition

----
PUT repository/process-definitions/{processDefinitionId}
----

**JSON体：**

[source,json,linenums]
----
{
  "action" : "activate",
  "includeProcessInstances" : "true",
  "date" : "2013-04-15T00:42:12Z"
}
----

参见暂停流程定义的<<processDefinitionActionBodyParameters,JSON体参数>>。

.激活一个流程定义 - 响应码
[options="header"]
|===============
|响应码|描述
|200|代表已激活流程。
|404|代表未找到请求的流程定义。
|409|代表请求的流程定义之前已经激活。

|===============


**成功响应体：**参见++repository/process-definitions/{processDefinitionId}++的响应


==== 获取一个流程定义的所有候选启动者 Get all candidate starters for a process-definition

----
GET repository/process-definitions/{processDefinitionId}/identitylinks
----


.获取一个流程定义的所有候选启动者 - URL 参数
[options="header"]
|===============
|参数|必填|值|描述
|processDefinitionId|是|String|要获取身份联系的流程定义的id。

|===============


.获取一个流程定义的所有候选启动者 - 响应码
[options="header"]
|===============
|响应码|描述
|200|代表已找到流程定义，并返回了请求的身份联系。
|404|代表未找到请求的流程定义。

|===============


**成功响应体：**

[source,json,linenums]
----
[
   {
      "url":"http://localhost:8182/repository/process-definitions/oneTaskProcess%3A1%3A4/identitylinks/groups/admin",
      "user":null,
      "group":"admin",
      "type":"candidate"
   },
   {
      "url":"http://localhost:8182/repository/process-definitions/oneTaskProcess%3A1%3A4/identitylinks/users/kermit",
      "user":"kermit",
      "group":null,
      "type":"candidate"
   }
]
----


==== 为一个流程定义添加一个候选启动者 Add a candidate starter to a process definition


----
POST repository/process-definitions/{processDefinitionId}/identitylinks
----

.为一个流程定义添加一个候选启动者 - URL 参数
[options="header"]
|===============
|参数|必填|值|描述
|processDefinitionId|是|String|流程定义的id。

|===============

**请求体（用户）：**

[source,json,linenums]
----
{
  "user" : "kermit"
}
----

**请求体（组）：**

[source,json,linenums]
----
{
  "groupId" : "sales"
}
----

.为一个流程定义添加一个候选启动者 - 响应码
[options="header"]
|===============
|响应码|描述
|201|代表已找到流程定义，并已添加身份联系。
|404|代表未找到请求的流程定义。

|===============


**成功响应体：**

[source,json,linenums]
----

{
  "url":"http://localhost:8182/repository/process-definitions/oneTaskProcess%3A1%3A4/identitylinks/users/kermit",
  "user":"kermit",
  "group":null,
  "type":"candidate"
}
----


==== 从一个流程定义中删除一个候选启动者 Delete a candidate starter from a process definition


----
DELETE repository/process-definitions/{processDefinitionId}/identitylinks/{family}/{identityId}
----

.从一个流程定义中删除一个候选启动者 - URL 参数
[options="header"]
|===============
|参数|必填|值|描述
|processDefinitionId|是|String|流程定义的id。
|family|是|String|为++users++或++groups++，取决于身份联系的类型。
|identityId|是|String|要从候选启动者中移除的userId或groupId。

|===============


.从一个流程定义中删除一个候选启动者 - 响应码
[options="header"]
|===============
|响应码|描述
|204|代表已找到流程定义，并已移除该身份联系。响应体设置为空。
|404|代表未找到请求的流程定义，或者流程定义中并没有匹配url的身份联系。

|===============


**成功响应体：**

[source,json,linenums]
----

{
  "url":"http://localhost:8182/repository/process-definitions/oneTaskProcess%3A1%3A4/identitylinks/users/kermit",
  "user":"kermit",
  "group":null,
  "type":"candidate"
}
----


==== 从一个流程定义中获取一个候选启动者 Get a candidate starter from a process definition

----
GET repository/process-definitions/{processDefinitionId}/identitylinks/{family}/{identityId}
----


.从一个流程定义中获取一个候选启动者 - URL 参数
[options="header"]
|===============
|参数|必填|值|描述
|processDefinitionId|是|String|流程定义的id。
|family|是|String|为++users++或++groups++，取决于身份联系的类型。
|identityId|是|String|要获取的候选启动者的userId或groupId。

|===============


.从一个流程定义中获取一个候选启动者 - 响应码
[options="header"]
|===============
|响应码|描述
|200|代表已找到流程定义，并已返回身份联系。
|404|代表未找到请求的流程定义，或者流程定义中并没有匹配url的身份联系。

|===============

**成功响应体：**

[source,json,linenums]
----
{
  "url":"http://localhost:8182/repository/process-definitions/oneTaskProcess%3A1%3A4/identitylinks/users/kermit",
  "user":"kermit",
  "group":null,
  "type":"candidate"
}
----

=== 模型 Models


==== 获取模型的列表 Get a list of models


----
GET repository/models
----

.获取模型的列表 - URL 查询参数
[options="header"]
|===============
|参数|必填|值|描述
|id|否|String|只返回给定id的模型。
|category|否|String|只返回给定分类的模型。
|categoryLike|否|String|只返回分类like给定值的模型。使用++%++字符作为通配符。
|categoryNotEquals|否|String|只返回不是给定分类的模型。
|name|否|String|只返回给定名字的模型。
|nameLike|否|String|只返回名字like给定值的模型。使用++%++字符作为通配符。
|key|否|String|只返回给定key的模型。
|deploymentId|否|String|只返回在给定部署中部署的模型。
|version|否|Integer|只返回给定版本的模型。
|latestVersion|否|Boolean|如果值为++true++，则只返回最新版本的模型。最好与++key++联合使用。如果值为++false++，忽略本参数，返回所有版本。
|deployed|否|Boolean|如果值为++true++，只返回已部署的模型。如果值为++false++，只返回未部署的模型（deploymentId为null）。
|tenantId|否|String|只返回给定tenantId的模型。
|tenantIdLike|否|String|只返回tenantId like给定值的模型。
|withoutTenantId|否|Boolean|如果值为++true++，则只返回没有设置tenantId的模型。如果值为++false++，则忽略++withoutTenantId++参数。
|sort|否|'id'（默认）、'category'、'createTime'、'key'、'lastUpdateTime'、'name'、'version'或'tenantId'|用于排序的参数，与'order'一起使用。

|===============

可以在这个URL中使用通用<<restPagingAndSort,分页与排序查询参数>>。

.获取模型的列表 - 响应码
[options="header"]
|===============
|响应码|描述
|200|代表查询成功，并返回了模型。
|400|代表传递的参数格式错误。状态描述中包含了额外信息。

|===============


**成功响应体：**

[source,json,linenums]
----
{
   "data":[
      {
         "name":"Model name",
         "key":"Model key",
         "category":"Model category",
         "version":2,
         "metaInfo":"Model metainfo",
         "deploymentId":"7",
         "id":"10",
         "url":"http://localhost:8182/repository/models/10",
         "createTime":"2013-06-12T14:31:08.612+0000",
         "lastUpdateTime":"2013-06-12T14:31:08.612+0000",
         "deploymentUrl":"http://localhost:8182/repository/deployments/7",
         "tenantId":null
      },

      ...

   ],
   "total":2,
   "start":0,
   "sort":"id",
   "order":"asc",
   "size":2
}
----


==== 获取一个模型 Get a model


----
GET repository/models/{modelId}
----

.获取一个模型 - URL 参数
[options="header"]
|===============
|参数|必填|值|描述
|modelId|是|String|要获取的模型的id。

|===============


.获取一个模型 - 响应码
[options="header"]
|===============
|响应码|描述
|200|代表已找到并返回模型。
|404|代表未找到请求的模型。

|===============


**成功响应体：**

[source,json,linenums]
----
{
   "id":"5",
   "url":"http://localhost:8182/repository/models/5",
   "name":"Model name",
   "key":"Model key",
   "category":"Model category",
   "version":2,
   "metaInfo":"Model metainfo",
   "deploymentId":"2",
   "deploymentUrl":"http://localhost:8182/repository/deployments/2",
   "createTime":"2013-06-12T12:31:19.861+0000",
   "lastUpdateTime":"2013-06-12T12:31:19.861+0000",
   "tenantId":null
}
----



==== 更新一个模型 Update a model

----
PUT repository/models/{modelId}
----

**请求体：**

[source,json,linenums]
----
{
   "name":"Model name",
   "key":"Model key",
   "category":"Model category",
   "version":2,
   "metaInfo":"Model metainfo",
   "deploymentId":"2",
   "tenantId":"updatedTenant"
}
----

所有的请求值都是可选的。例如，可以只在请求体的JSON对象中包含'name'属性，则只更新模型的名字，而不影响其它所有字段。当显式包含了一个属性，并设置为null，则模型值将更新为null。例如：++{"metaInfo" : null}++将清空模型的metaInfo。

.更新一个模型 - 响应码
[options="header"]
|===============
|响应码|描述
|200|代表已找到并更新了模型。
|404|代表未找到请求的模型。

|===============

**成功响应体：**

[source,json,linenums]
----
{
   "id":"5",
   "url":"http://localhost:8182/repository/models/5",
   "name":"Model name",
   "key":"Model key",
   "category":"Model category",
   "version":2,
   "metaInfo":"Model metainfo",
   "deploymentId":"2",
   "deploymentUrl":"http://localhost:8182/repository/deployments/2",
   "createTime":"2013-06-12T12:31:19.861+0000",
   "lastUpdateTime":"2013-06-12T12:31:19.861+0000",
   "tenantId":""updatedTenant"
}
----


==== 创建一个模型 Create a model

----
POST repository/models
----

**请求体：**

[source,json,linenums]
----
{
   "name":"Model name",
   "key":"Model key",
   "category":"Model category",
   "version":1,
   "metaInfo":"Model metainfo",
   "deploymentId":"2",
   "tenantId":"tenant"
}
----

所有的请求值都是可选的。例如，可以只在请求体的JSON对象中包含'name'属性，则只设置模型的名字，其它所有字段都为null。

.创建一个模型 - 响应码
[options="header"]
|===============
|响应码|描述
|201|代表已创建模型。

|===============

**成功响应体：**

[source,json,linenums]
----
{
   "id":"5",
   "url":"http://localhost:8182/repository/models/5",
   "name":"Model name",
   "key":"Model key",
   "category":"Model category",
   "version":1,
   "metaInfo":"Model metainfo",
   "deploymentId":"2",
   "deploymentUrl":"http://localhost:8182/repository/deployments/2",
   "createTime":"2013-06-12T12:31:19.861+0000",
   "lastUpdateTime":"2013-06-12T12:31:19.861+0000",
   "tenantId":"tenant"
}
----


==== 删除一个模型 Delete a model

----
DELETE repository/models/{modelId}
----


.删除一个模型 - URL 参数
[options="header"]
|===============
|参数|必填|值|描述
|modelId|是|String|要删除的模型的id。

|===============


.删除一个模型 - 响应码
[options="header"]
|===============
|响应码|描述
|204|代表已找到并删除了模型。响应体设置为空。
|404|代表未找到请求的模型。

|===============


==== 获取一个模型的编辑器源码 Get the editor source for a model


----
GET repository/models/{modelId}/source
----


.获取一个模型的编辑器源码 - URL 参数
[options="header"]
|===============
|参数|必填|值|描述
|modelId|是|String|模型的id。

|===============


.获取一个模型的编辑器源码 - 响应码
[options="header"]
|===============
|响应码|描述
|200|代表已找到模型，并返回了源码。
|404|代表未找到请求的模型。

|===============



**成功响应体：**响应体包含了模型的原始编辑器源码。无论源码的content是什么，响应的content-type都设置为++application/octet-stream++。


==== 设置一个模型的编辑器源码 Set the editor source for a model

----
PUT repository/models/{modelId}/source
----

.设置一个模型的编辑器源码 - URL 参数
[options="header"]
|===============
|参数|必填|值|描述
|modelId|是|String|模型的id。

|===============


**请求体：**

请求需要是++multipart/form-data++类型的。需要有唯一的file-part，包含源码的二进制值。

.设置一个模型的编辑器源码 - 响应码
[options="header"]
|===============
|响应码|描述
|200|代表已找到模型，并更新了源码。
|404|代表未找到请求的模型。

|===============

**成功响应体：**响应体包含了模型的原始编辑器源码。无论源码的content是什么，响应的content-type都设置为++application/octet-stream++。


==== 获取一个模型的附加编辑器源码 Get the extra editor source for a model

----
GET repository/models/{modelId}/source-extra
----

.获取一个模型的附加编辑器源码 - URL 参数
[options="header"]
|===============
|参数|必填|值|描述
|modelId|是|String|模型的id。

|===============


.获取一个模型的附加编辑器源码 - 响应码
[options="header"]
|===============
|响应码|描述
|200|代表已找到模型，并返回了源码。
|404|代表未找到请求的模型。

|===============


**成功响应体：**响应体包含了模型的原始编辑器源码。无论源码的content是什么，响应的content-type都设置为++application/octet-stream++。


==== 设置一个模型的附加编辑器源码 Set the extra editor source for a model


----
PUT repository/models/{modelId}/source-extra
----

.设置一个模型的附加编辑器源码 - URL 参数
[options="header"]
|===============
|参数|必填|值|描述
|modelId|是|String|模型的id。

|===============

**请求体：**


请求需要是++multipart/form-data++类型的。需要有唯一的file-part，包含源码的二进制值。

.设置一个模型的附加编辑器源码 - 响应码
[options="header"]
|===============
|响应码|描述
|200|代表已找到模型，并更新了附加源码。
|404|代表未找到请求的模型。

|===============


**成功响应体：**响应体包含了模型的原始编辑器源码。无论源码的content是什么，响应的content-type都设置为++application/octet-stream++。


=== 流程实例 Process Instances

==== 获取一个流程实例 Get a process instance

----
GET runtime/process-instances/{processInstanceId}
----

.获取一个流程实例 - URL 参数
[options="header"]
|===============
|参数|必填|值|描述
|processInstanceId|是|String|要获取的流程实例的id。

|===============


.获取一个流程实例 - 响应码
[options="header"]
|===============
|响应码|描述
|200|代表已找到并返回了流程实例。
|404|代表未找到请求的流程实例。

|===============


**成功响应体：**

[source,json,linenums]
----
{
   "id":"7",
   "url":"http://localhost:8182/runtime/process-instances/7",
   "businessKey":"myBusinessKey",
   "suspended":false,
   "processDefinitionUrl":"http://localhost:8182/repository/process-definitions/processOne%3A1%3A4",
   "activityId":"processTask",
   "tenantId": null
}
----


==== 删除一个流程实例 Delete a process instance

----
DELETE runtime/process-instances/{processInstanceId}
----

.删除一个流程实例 - URL 参数
[options="header"]
|===============
|参数|必填|值|描述
|processInstanceId|是|String|要删除的流程实例的id。

|===============


.删除一个流程实例 - 响应码
[options="header"]
|===============
|响应码|描述
|204|代表已找到并删除了流程实例。响应体设置为空
|404|代表未找到请求的流程实例。

|===============


==== 激活或暂停一个流程实例 Activate or suspend a process instance


----
PUT runtime/process-instances/{processInstanceId}
----


.激活或暂停一个流程实例 - URL 参数
[options="header"]
|===============
|参数|必填|值|描述
|processInstanceId|是|String|要激活/暂停的流程实例的id。

|===============

**请求体（暂停）：**

[source,json,linenums]
----
{
   "action":"suspend"
}
----

**请求体（激活）：**

[source,json,linenums]
----
{
   "action":"activate"
}
----

.激活或暂停一个流程实例 - 响应码
[options="header"]
|===============
|响应码|描述
|200|代表已找到流程实例，并执行了操作。
|400|代表提供了非法的操作。
|404|代表未找到请求的流程实例。
|409|代表请求的流程实例操作无法执行，因为流程实例之前已经激活/暂停了。

|===============



==== 启动一个流程实例 Start a process instance


----
POST runtime/process-instances
----

**请求体（通过流程定义id启动）：**

[source,json,linenums]
----
{
   "processDefinitionId":"oneTaskProcess:1:158",
   "businessKey":"myBusinessKey",
   "variables": [
      {
        "name":"myVar",
        "value":"This is a variable",
      }
   ]
}
----

**请求体（通过流程定义key启动）：**

[source,json,linenums]
----
{
   "processDefinitionKey":"oneTaskProcess",
   "businessKey":"myBusinessKey",
   "tenantId": "tenant1",
   "variables": [
      {
        "name":"myVar",
        "value":"This is a variable",
      }
   ]
}
----

**请求体（通过消息启动）：**

[source,json,linenums]
----
{
   "message":"newOrderMessage",
   "businessKey":"myBusinessKey",
   "tenantId": "tenant1",
   "variables": [
      {
        "name":"myVar",
        "value":"This is a variable",
      }
   ]
}
----

请求体中只能使用++processDefinitionId++、++processDefinitionKey++与++message++中的一个。++businessKey++、++variables++与++tenantId++参数是可选的。如果省略了++tenantId++，则将使用默认租户。关于变量格式的更多信息可以在<<restVariables,REST变量章节>>找到。请注意提供的变量范围将被忽略，流程变量总是++local++的。


.启动一个流程实例 - 响应码
[options="header"]
|===============
|响应码|描述
|201|代表已创建流程实例。
|400|代表（通过id或key）未找到流程定义，或者发送给定消息并未启动流程，或者传递了不合法的变量。状态描述中包含了关于错误的额外信息。

|===============


**成功响应体：**

[source,json,linenums]
----
{
   "id":"7",
   "url":"http://localhost:8182/runtime/process-instances/7",
   "businessKey":"myBusinessKey",
   "suspended":false,
   "processDefinitionUrl":"http://localhost:8182/repository/process-definitions/processOne%3A1%3A4",
   "activityId":"processTask",
   "tenantId" : null
}
----


[[restProcessInstancesGet]]


==== 列表流程实例 List of process instances

----
GET runtime/process-instances
----

.列表流程实例 - URL 查询参数
[options="header"]
|===============
|参数|必填|值|描述
|id|否|String|只返回给定id的流程实例。
|processDefinitionKey|否|String|只返回给定流程定义key的流程实例。
|processDefinitionId|否|String|只返回给定流程定义id的流程实例。
|businessKey|否|String|只返回给定businessKey的流程实例。
|involvedUser|否|String|只返回给定用户参与的流程实例。
|suspended|否|Boolean|如果值为++true++，则只返回暂停的流程实例。如果值为++false++，则只返回未暂停（激活）的流程实例。
|superProcessInstanceId|否|String|只返回给定父流程实例id的流程实例（使用调用活动的流程）。
|subProcessInstanceId|否|String|只返回给定子流程实例id的流程实例（通过调用活动启动的流程）。
|excludeSubprocesses|否|Boolean|只返回不是子流程的流程实例。
|includeProcessVariables|否|Boolean|是否在结果中包含流程变量。
|tenantId|否|String|只返回给定tenantId的流程实例。
|tenantIdLike|否|String|只返回tenantId like给定值的流程实例。
|withoutTenantId|否|Boolean|如果值为++true++，则只返回没有设置tenantId的流程实例。如果值为++false++，则忽略++withoutTenantId++参数。
|sort|否|String|排序字段，需要是++id++（默认）、++processDefinitionId++、++tenantId++或++processDefinitionKey++中的一个。

|===============


可以在这个URL中使用通用<<restPagingAndSort,分页与排序查询参数>>。

.列表流程实例 - 响应码
[options="header"]
|===============
|响应码|描述
|200|代表请求成功，并返回了流程实例。
|400|代表传递的参数格式错误 . 状态描述中包含了额外信息。

|===============


**成功响应体：**

[source,json,linenums]
----
{
   "data":[
      {
         "id":"7",
         "url":"http://localhost:8182/runtime/process-instances/7",
         "businessKey":"myBusinessKey",
         "suspended":false,
         "processDefinitionUrl":"http://localhost:8182/repository/process-definitions/processOne%3A1%3A4",
         "activityId":"processTask",
         "tenantId" : null
      }


   ],
   "total":2,
   "start":0,
   "sort":"id",
   "order":"asc",
   "size":2
}
----


==== 查询流程实例 Query process instances

----
POST query/process-instances
----

**请求体：**

[source,json,linenums]
----
{
  "processDefinitionKey":"oneTaskProcess",
  "variables":
  [
    {
        "name" : "myVariable",
        "value" : 1234,
        "operation" : "equals",
        "type" : "long"
    }
  ]
}
----

请求体可以包含所有在<<restProcessInstancesGet,列表流程实例>>URL查询中可用的过滤器。另外，也可以在查询中包含一个变量的数组，使用<<restQueryVariable, 这里描述>>的格式。


可以在这个URL中使用通用<<restPagingAndSort,分页与排序查询参数>>。


.查询流程实例 - 响应码
[options="header"]
|===============
|响应码|描述
|200|代表请求成功，并返回了流程实例。
|400|代表传递的参数格式错误。状态描述中包含了额外信息。

|===============

**成功响应体：**

[source,json,linenums]
----
{
   "data":[
      {
         "id":"7",
         "url":"http://localhost:8182/runtime/process-instances/7",
         "businessKey":"myBusinessKey",
         "suspended":false,
         "processDefinitionUrl":"http://localhost:8182/repository/process-definitions/processOne%3A1%3A4",
         "activityId":"processTask",
         "tenantId" : null
      }


   ],
   "total":2,
   "start":0,
   "sort":"id",
   "order":"asc",
   "size":2
}
----


==== 获取一个流程实例的流程图 Get diagram for a process instance

----
GET runtime/process-instances/{processInstanceId}/diagram
----

.获取一个流程实例的流程图 - URL 参数
[options="header"]
|===============
|参数|必填|值|描述
|processInstanceId|是|String|要获取流程图的流程实例的id。

|===============


.获取一个流程实例的流程图 - 响应码
[options="header"]
|===============
|响应码|描述
|200|代表已找到流程实例，并已返回了流程图。
|400|代表已找到请求的流程实例，但该流程未包含任何图形信息（BPMN：DI），因此不能创建流程图。
|404|代表未找到请求的流程实例。

|===============


**成功响应体：**

[source,json,linenums]
----
{
   "id":"7",
   "url":"http://localhost:8182/runtime/process-instances/7",
   "businessKey":"myBusinessKey",
   "suspended":false,
   "processDefinitionUrl":"http://localhost:8182/repository/process-definitions/processOne%3A1%3A4",
   "activityId":"processTask"
}
----


==== 获取流程实例的参与人 Get involved people for process instance

----
GET runtime/process-instances/{processInstanceId}/identitylinks
----


.获取流程实例的参与人 - URL 参数
[options="header"]
|===============
|参数|必填|值|描述
|processInstanceId|是|String|要查询联系的流程实例的id。

|===============


.获取流程实例的参与人 - 响应码
[options="header"]
|===============
|响应码|描述
|200|代表已找到流程实例，并已返回联系。
|404|代表未找到请求的流程实例。

|===============


**成功响应体：**

[source,json,linenums]
----
[
   {
      "url":"http://localhost:8182/runtime/process-instances/5/identitylinks/users/john/customType",
      "user":"john",
      "group":null,
      "type":"customType"
   },
   {
      "url":"http://localhost:8182/runtime/process-instances/5/identitylinks/users/paul/candidate",
      "user":"paul",
      "group":null,
      "type":"candidate"
   }
]
----

请注意++groupId++永远为null，因为只有用户才能参与流程实例。


==== 为一个流程实例添加一个参与用户 Add an involved user to a process instance


----
POST runtime/process-instances/{processInstanceId}/identitylinks
----

.为一个流程实例添加一个参与用户 - URL 参数
[options="header"]
|===============
|参数|必填|值|描述
|processInstanceId|是|String|要添加联系的流程实例。

|===============


**请求体：**

[source,json,linenums]
----
{
  "userId":"kermit",
  "type":"participant"
}
----

++userId++与++type++都是必填的。


.为一个流程实例添加一个参与用户 - 响应码
[options="header"]
|===============
|响应码|描述
|201|代表已找到流程实例，并已返回联系。
|400|代表请求体中未包含userId或type。
|404|代表未找到请求的流程实例。

|===============


**成功响应体：**

[source,json,linenums]
----
{
   "url":"http://localhost:8182/runtime/process-instances/5/identitylinks/users/john/customType",
   "user":"john",
   "group":null,
   "type":"customType"
}
----

请注意++groupId++永远为null，因为只有用户才能参与流程实例。


==== 从一个流程实例中移除一个参与用户 Remove an involved user to from process instance

----
DELETE runtime/process-instances/{processInstanceId}/identitylinks/users/{userId}/{type}
----


.从一个流程实例中移除一个参与用户 - URL 参数
[options="header"]
|===============
|参数|必填|值|描述
|processInstanceId|是|String|流程实例的id。
|userId|是|String|要删除联系的用户的id。
|type|是|String|要删除的联系的类型。

|===============


.从一个流程实例中移除一个参与用户 - 响应码
[options="header"]
|===============
|响应码|描述
|204|代表已找到流程实例，并已删除联系。响应体设置为空
|404|代表未找到请求的流程实例，或者要删除的联系不存在。响应状态中包含了关于错误的额外信息。
|===============

**成功响应体：**

[source,json,linenums]
----
{
   "url":"http://localhost:8182/runtime/process-instances/5/identitylinks/users/john/customType",
   "user":"john",
   "group":null,
   "type":"customType"
}
----


请注意++groupId++永远为null，因为只有用户才能参与流程实例。


==== 列表一个流程实例的变量 List of variables for a process instance

----
GET runtime/process-instances/{processInstanceId}/variables
----

.列表一个流程实例的变量 - URL 参数
[options="header"]
|===============
|参数|必填|值|描述
|processInstanceId|是|String|要列表变量的流程实例的id。

|===============



.列表一个流程实例的变量 - 响应码
[options="header"]
|===============
|响应码|描述
|200|代表已找到流程实例，并返回了变量。
|404|代表未找到请求的流程实例。

|===============


**成功响应体：**

[source,json,linenums]
----
[
   {
      "name":"intProcVar",
      "type":"integer",
      "value":123,
      "scope":"local"
   },
   {
      "name":"byteArrayProcVar",
      "type":"binary",
      "value":null,
      "valueUrl":"http://localhost:8182/runtime/process-instances/5/variables/byteArrayProcVar/data",
      "scope":"local"
   }
]
----

如果变量是二进制变量或序列化值，则++valueUrl++指向获取原始值的URL。如果是一个简单变量，则在响应中显示值。请注意只会返回++local++范围的变量，因为流程实例变量没有++global++范围。



==== 获取一个流程实例的一个变量 Get a variable for a process instance


----
GET runtime/process-instances/{processInstanceId}/variables/{variableName}
----


.获取一个流程实例的一个变量 - URL 参数
[options="header"]
|===============
|参数|必填|值|描述
|processInstanceId|是|String|要获取变量的流程实例的id。
|variableName|是|String|要获取的变量的名字。

|===============


.获取一个流程实例的一个变量 - 响应码
[options="header"]
|===============
|响应码|描述
|200|代表已找到流程实例及变量，并返回了变量。
|400|代表请求体不完整，或者包含不合法值。状态描述中包含了关于错误的额外信息。
|404|代表未找到请求的流程实例，或者流程实例中没有给定名字的变量。状态描述中包含了关于错误的额外信息。

|===============


**成功响应体：**

[source,json,linenums]
----
   {
      "name":"intProcVar",
      "type":"integer",
      "value":123,
      "scope":"local"
   }
----

如果变量是二进制变量或序列化值，则++valueUrl++指向获取原始值的URL。如果是一个简单变量，则在响应中显示值。请注意只会返回++local++范围的变量，因为流程实例变量没有++global++范围。


==== 为一个流程实例创建（或更新）变量 Create (or update) variables on a process instance

----
POST runtime/process-instances/{processInstanceId}/variables
----

----
PUT runtime/process-instances/{processInstanceId}/variables
----

当使用++POST++时，会创建所有传递的变量。如果流程实例中已经存在某个变量，则请求结果为错误（409 - 冲突）。当使用++PUT++时，会创建流程实例中不存在的变量；已存在变量的将会被覆盖，而没有错误。

.为一个流程实例创建（或更新）变量 - URL 参数
[options="header"]
|===============
|参数|必填|值|描述
|processInstanceId|是|String|要操作变量的流程实例的id。

|===============


**请求体：**

----
[
   {
      "name":"intProcVar"
      "type":"integer"
      "value":123
   },

   ...
]
----

请求体的数组中可以传递任意数量的变量。可以在<<restVariables,REST变量章节>>找到关于变量格式的更多信息。请注意范围将被忽略，流程实例中只能设置++local++变量。

.为一个流程实例创建（或更新）变量 - 响应码
[options="header"]
|===============
|响应码|描述
|201|代表已找到流程实例，并已创建变量。
|400|代表请求体不完整，或含有非法值。状态描述中包含了关于错误的额外信息。
|404|代表未找到请求的流程实例。
|409|代表已找到流程实例，但其已包含了给定名字的变量（只在使用POST方法时抛出）。改用更新方法。

|===============


**成功响应体：**

----
[
   {
      "name":"intProcVar",
      "type":"integer",
      "value":123,
      "scope":"local"
   },

   ...

]
----


==== 为一个流程实例更新一个变量 Update a single variable on a process instance

----
PUT runtime/process-instances/{processInstanceId}/variables/{variableName}
----

.为一个流程实例更新一个变量 - URL 参数
[options="header"]
|===============
|参数|必填|值|描述
|processInstanceId|是|String|要操作变量的流程实例的id。
|variableName|是|String|要更新的变量名。

|===============

**请求体：**

[source,json,linenums]
----
 {
    "name":"intProcVar"
    "type":"integer"
    "value":123
 }
----


请求体的数组中可以传递任意数量的变量。可以在<<restVariables,REST变量章节>>找到关于变量格式的更多信息。请注意范围将被忽略，流程实例中只能设置++local++变量。

.为一个流程实例更新一个变量 - 响应码
[options="header"]
|===============
|响应码|描述
|200|代表已找到流程实例与变量，并已更新变量。
|404|代表未找到请求的流程实例，或者流程实例中没有给定名字的变量。状态描述中包含了关于错误的额外信息。

|===============


**成功响应体：**

[source,json,linenums]
----
{
  "name":"intProcVar",
  "type":"integer",
  "value":123,
  "scope":"local"
}
----


如果变量是二进制变量或序列化值，则++valueUrl++指向获取原始值的URL。如果是一个简单变量，则在响应中显示值。请注意只会返回++local++范围的变量，因为流程实例变量没有++global++范围。

==== 为一个流程实例创建一个新的二进制变量 Create a new binary variable on a process-instance

----
POST runtime/process-instances/{processInstanceId}/variables
----


.为一个流程实例创建一个新的二进制变量 - URL 参数
[options="header"]
|===============
|参数|必填|值|描述
|processInstanceId|是|String|The id of the process instance to create the new variable for.

|===============



**请求体：**请求需要是++multipart/form-data++类型的。需要有唯一的file-part，包含变量的二进制值。另外，也可以使用下列额外的form-fields：

* ++name++: 变量需要的名字。
* ++type++: 创建的变量的类型。如果忽略，则使用++binary++，并且将请求中的二进制数据保存为字节数组。


**成功响应体：**

[source,json,linenums]
----
{
  "name" : "binaryVariable",
  "scope" : "local",
  "type" : "binary",
  "value" : null,
  "valueUrl" : "http://.../runtime/process-instances/123/variables/binaryVariable/data"
}
----


.为一个流程实例创建一个新的二进制变量 - 响应码
[options="header"]
|===============
|响应码|描述
|201|代表已创建变量，并已返回结果。
|400|代表缺少要创建的变量名。状态消息提供了额外信息。
|404|代表未找到请求的流程实例。
|409|代表流程实例中已经有给定名字的变量。改用PUT方法更新任务变量。
|415|代表序列化数据中包含了一个运行Activiti引擎的JVM中不存在的类的对象，因此不能反序列化。

|===============



==== 为一个流程实例更新一个已有二进制变量 Update an existing binary variable on a process-instance

----
PUT runtime/process-instances/{processInstanceId}/variables
----

.为一个流程实例更新一个已有二进制变量 - URL 参数
[options="header"]
|===============
|参数|必填|值|描述
|processInstanceId|是|String|要更新变量的流程实例的id。

|===============

**请求体：**请求需要是++multipart/form-data++类型的。需要有唯一的file-part，包含变量的二进制值。另外，也可以使用下列额外的form-fields：

* ++name++: 变量需要的名字。
* ++type++: 创建的变量的类型。如果忽略，则使用++binary++，并且将请求中的二进制数据保存为字节数组。

**成功响应体：**

[source,json,linenums]
----
{
  "name" : "binaryVariable",
  "scope" : "local",
  "type" : "binary",
  "value" : null,
  "valueUrl" : "http://.../runtime/process-instances/123/variables/binaryVariable/data"
}
----


.为一个流程实例更新一个已有二进制变量 - 响应码
[options="header"]
|===============
|响应码|描述
|200|代表已更新变量，并已返回结果。
|400|代表缺少要更新的变量名。状态消息提供了额外信息。
|404|代表未找到请求的流程实例，或者流程实例中没有给定名字的变量。
|415|代表序列化数据中包含了一个运行Activiti引擎的JVM中不存在的类的对象，因此不能反序列化。

|===============



=== 执行 Executions


==== 获取一个执行 Get an execution

----
GET runtime/executions/{executionId}
----


.获取一个执行 - URL 参数
[options="header"]
|===============
|参数|必填|值|描述
|executionId|是|String|要获取的执行的id。

|===============


.获取一个执行 - 响应码
[options="header"]
|===============
|响应码|描述
|200|代表已找到并返回执行。
|404|代表未找到执行

|===============


**成功响应体：**

[source,json,linenums]
----
{
   "id":"5",
   "url":"http://localhost:8182/runtime/executions/5",
   "parentId":null,
   "parentUrl":null,
   "processInstanceId":"5",
   "processInstanceUrl":"http://localhost:8182/runtime/process-instances/5",
   "suspended":false,
   "activityId":null,
   "tenantId": null
}
----


==== 对一个执行进行操作 Execute an action on an execution


----
PUT runtime/executions/{executionId}
----


.对一个执行进行操作 - URL 参数
[options="header"]
|===============
|参数|必填|值|描述
|executionId|是|String|The id of the execution to execute action on.

|===============

**请求体（为一个执行发信号）：**

[source,json,linenums]
----
{
  "action":"signal"
}
----

**请求体（为一个执行发信号接收事件）：**

[source,json,linenums]
----
{
  "action":"signalEventReceived",
  "signalName":"mySignal"
  "variables": [  ]
}
----

通知执行，已经接收到了一个信号事件，要求有一个++signalName++参数。可以传递可选的++variables++，将在进行操作前设置到执行中。

**请求体（为一个执行发消息接收事件）：**

[source,json,linenums]
----
{
  "action":"messageEventReceived",
  "messageName":"myMessage"
  "variables": [  ]
}
----

通知执行，已经接收到了一个消息事件，要求有一个++messageName++参数。可以传递可选的++variables++，将在进行操作前设置到执行中。

.对一个执行进行操作 - 响应码
[options="header"]
|===============
|响应码|描述
|200|代表已找到执行，并进行了操作。
|204|代表找到了执行，进行了操作，该操作导致执行结束。
|400|代表请求了非法的操作，请求中缺少了必要的参数，或者传递了非法的变量。状态描述中包含了关于错误的额外信息。
|404|代表未找到执行

|===============

**成功响应体（当执行并未因该操作结束时）：**

[source,json,linenums]
----
{
   "id":"5",
   "url":"http://localhost:8182/runtime/executions/5",
   "parentId":null,
   "parentUrl":null,
   "processInstanceId":"5",
   "processInstanceUrl":"http://localhost:8182/runtime/process-instances/5",
   "suspended":false,
   "activityId":null,
   "tenantId" : null
}
----


==== 获取一个执行中的激活活动 Get active activities in an execution

----
GET runtime/executions/{executionId}/activities
----

返回执行中与所有子执行中（以及它们的子执行，递归）激活的所有活动。

.获取一个执行中的激活活动 - URL 参数
[options="header"]
|===============
|参数|必填|值|描述
|executionId|是|String|要获取活动的执行的id。

|===============


.获取一个执行中的激活活动 - 响应码
[options="header"]
|===============
|响应码|描述
|200|代表已找到执行，并已返回了活动。
|404|代表未找到执行

|===============


**成功响应体：**

[source,json,linenums]
----
[
  "userTaskForManager",
  "receiveTask"
]
----


[[restExecutionsGet]]


==== 列表执行 List of executions


----
GET runtime/executions
----

.列表执行 - URL 查询参数
[options="header"]
|===============
|参数|必填|值|描述
|id|否|String|只返回给定id的执行。
|activityId|否|String|只返回给定activity id的执行。
|processDefinitionKey|否|String|只返回给定流程定义key的执行。
|processDefinitionId|否|String|只返回给定流程定义id的执行。
|processInstanceId|否|String|只返回给定流程实例中的执行。
|messageEventSubscriptionName|否|String|只返回订阅了给定名字的消息的执行。
|signalEventSubscriptionName|否|String|只返回订阅了给定名字的信号的执行。
|parentId|否|String|只返回给定执行的直接子执行。
|tenantId|否|String|只返回给定tenantId的执行。
|tenantIdLike|否|String|只返回tenantId like给定值的执行。
|withoutTenantId|否|Boolean|如果值为++true++，则只返回未设置tenantId的执行。如果值为++false++，则忽略++withoutTenantId++参数。
|sort|否|String|排序字段，需要为++processInstanceId++（默认）、++processDefinitionId++、++processDefinitionKey++或++tenantId++。

|===============

可以在这个URL中使用通用<<restPagingAndSort,分页与排序查询参数>>。

.列表执行 - 响应码
[options="header"]
|===============
|响应码|描述
|200|代表请求成功，并返回了执行。
|400|代表传递的参数格式错误 . 状态描述中包含了额外信息。

|===============


**成功响应体：**

[source,json,linenums]
----
{
   "data":[
      {
         "id":"5",
         "url":"http://localhost:8182/runtime/executions/5",
         "parentId":null,
         "parentUrl":null,
         "processInstanceId":"5",
         "processInstanceUrl":"http://localhost:8182/runtime/process-instances/5",
         "suspended":false,
         "activityId":null,
         "tenantId":null
      },
      {
         "id":"7",
         "url":"http://localhost:8182/runtime/executions/7",
         "parentId":"5",
         "parentUrl":"http://localhost:8182/runtime/executions/5",
         "processInstanceId":"5",
         "processInstanceUrl":"http://localhost:8182/runtime/process-instances/5",
         "suspended":false,
         "activityId":"processTask",
         "tenantId":null
      }
   ],
   "total":2,
   "start":0,
   "sort":"processInstanceId",
   "order":"asc",
   "size":2
}
----



==== 查询执行 Query executions


----
POST query/executions
----

**请求体：**

[source,json,linenums]
----
{
  "processDefinitionKey":"oneTaskProcess",
  "variables":
  [
    {
        "name" : "myVariable",
        "value" : 1234,
        "operation" : "equals",
        "type" : "long"
    }
  ],
  "processInstanceVariables":
  [
    {
        "name" : "processVariable",
        "value" : "some string",
        "operation" : "equals",
        "type" : "string"
    }
  ]
}
----

请求体可以包含所有在<<restExecutionsGet,列表执行>>URL查询中可用的过滤器。另外，也可以在查询中包含一个++variables++与++processInstanceVariables++的数组，使用<<restQueryVariable, 这里描述>>的格式。

可以在这个URL中使用通用<<restPagingAndSort,分页与排序查询参数>>。

.查询执行 - 响应码
[options="header"]
|===============
|响应码|描述
|200|代表请求成功，并返回了执行。
|400|代表传递的参数格式错误 . 状态描述中包含了额外信息。

|===============

**成功响应体：**

[source,json,linenums]
----
{
   "data":[
      {
         "id":"5",
         "url":"http://localhost:8182/runtime/executions/5",
         "parentId":null,
         "parentUrl":null,
         "processInstanceId":"5",
         "processInstanceUrl":"http://localhost:8182/runtime/process-instances/5",
         "suspended":false,
         "activityId":null,
         "tenantId":null
      },
      {
         "id":"7",
         "url":"http://localhost:8182/runtime/executions/7",
         "parentId":"5",
         "parentUrl":"http://localhost:8182/runtime/executions/5",
         "processInstanceId":"5",
         "processInstanceUrl":"http://localhost:8182/runtime/process-instances/5",
         "suspended":false,
         "activityId":"processTask",
         "tenantId":null
      }
   ],
   "total":2,
   "start":0,
   "sort":"processInstanceId",
   "order":"asc",
   "size":2
}
----



==== 列表一个执行中的变量 List of variables for an execution

----
GET runtime/executions/{executionId}/variables?scope={scope}
----


.列表一个执行中的变量 - URL 参数
[options="header"]
|===============
|参数|必填|值|描述
|executionId|是|String|要列表变量的执行的id。
|scope|否|String|可以为++local++或+global++。若省略，则同时返回本地与全局范围变量。

|===============


.列表一个执行中的变量 - 响应码
[options="header"]
|===============
|响应码|描述
|200|代表已找到执行，并已返回变量。
|404|代表未找到请求的执行。

|===============


**成功响应体：**

[source,json,linenums]
----
[
   {
      "name":"intProcVar",
      "type":"integer",
      "value":123,
      "scope":"global"
   },
   {
      "name":"byteArrayProcVar",
      "type":"binary",
      "value":null,
      "valueUrl":"http://localhost:8182/runtime/process-instances/5/variables/byteArrayProcVar/data",
      "scope":"local"
   }


]
----

如果变量是二进制变量或序列化值，则++valueUrl++指向获取原始值的URL。如果是一个简单变量，则在响应中显示值。请注意只会返回++local++范围的变量，因为流程实例变量没有++global++范围。


==== 获取一个执行的一个变量 Get a variable for an execution

----
GET runtime/executions/{executionId}/variables/{variableName}?scope={scope}
----


.获取一个执行的一个变量 - URL 参数
[options="header"]
|===============
|参数|必填|值|描述
|executionId|是|String|要获取变量的执行的id
|variableName|是|String|要获取的变量名。
|scope|否|String|++local++或+global++。若省略，则（存在时）返回本地变量。不存在本地变量时，则（存在时）返回全局变量。

|===============


.获取一个执行的一个变量 - 响应码
[options="header"]
|===============
|响应码|描述
|200|代表已找到执行与变量，并已返回变量。
|400|代表请求体不完整，或者包含不合法值。状态描述中包含了关于错误的额外信息。
|404|代表未找到请求的执行，或者在请求的范围内执行没有给定名字的变量（若省略了范围查询条件，则本地与全局范围中都没有该变量）。状态描述中包含了关于错误的额外信息。

|===============



**成功响应体：**

[source,json,linenums]
----
   {
      "name":"intProcVar",
      "type":"integer",
      "value":123,
      "scope":"local"
   }
----


如果变量是二进制变量或序列化值，则++valueUrl++指向获取原始值的URL。如果是一个简单变量，则在响应中显示值。

==== 为一个执行创建（或更新）变量 Create (or update) variables on an execution

----
POST runtime/executions/{executionId}/variables
----

----
PUT runtime/executions/{executionId}/variables
----

当使用++POST++时，会创建所有传递的变量。如果执行中已经存在某个变量，则请求结果为错误（409 - 冲突）。当使用++PUT++时，会创建执行中不存在的变量；已存在变量的将会被覆盖，而没有错误。

.为一个执行创建（或更新）变量 - URL 参数
[options="header"]
|===============
|参数|必填|值|描述
|executionId|是|String|要操作变量的执行的id。

|===============



**请求体：**

[source,json,linenums]
----
[
   {
      "name":"intProcVar"
      "type":"integer"
      "value":123,
      "scope":"local"
   }



]
----

**请注意只能提供相同范围的变量。如果请求体数组中包含了不同范围的变量，则请求结果为错误（400 - 错误请求）。**请求体的数组中可以传递任意数量的变量。可以在<<restVariables,REST变量章节>>找到关于变量格式的更多信息。（原文如此）请注意范围将被忽略，流程实例中只能设置++local++变量。

.为一个执行创建（或更新）变量 - 响应码
[options="header"]
|===============
|响应码|描述
|201|代表已找到执行，并已创建变量。
|400|代表请求体不完整，或者包含不合法值。状态描述中包含了关于错误的额外信息。
|404|代表未找到请求的执行。
|409|代表已找到执行，但其已包含了给定名字的变量（只在使用POST方法时抛出）。改用更新方法。

|===============


**成功响应体：**

[source,json,linenums]
----
[
   {
      "name":"intProcVar",
      "type":"integer",
      "value":123,
      "scope":"local"
   }



]
----



==== 为一个执行更新一个变量 Update a variable on an execution


----
PUT runtime/executions/{executionId}/variables/{variableName}
----


.为一个执行更新一个变量 - URL 参数
[options="header"]
|===============
|参数|必填|值|描述
|executionId|是|String|要更新变量的执行的id。
|variableName|是|String|要更新的变量名。

|===============


**请求体：**

[source,json,linenums]
----
 {
    "name":"intProcVar"
    "type":"integer"
    "value":123,
    "scope":"global"
 }
----

可以在<<restVariables,REST变量章节>>找到关于变量格式的更多信息。

.为一个执行更新一个变量 - 响应码
[options="header"]
|===============
|响应码|描述
|200|代表已找到执行与变量，并已更新变量。
|404|代表未找到请求的执行，或者执行没有给定名字的变量。状态描述中包含了关于错误的额外信息。

|===============


**成功响应体：**

[source,json,linenums]
----
   {
      "name":"intProcVar",
      "type":"integer",
      "value":123,
      "scope":"global"
   }
----


如果变量是二进制变量或序列化值，则++valueUrl++指向获取原始值的URL。如果是一个简单变量，则在响应中显示值。


==== 为一个执行创建一个新的二进制变量 Create a new binary variable on an execution

----
POST runtime/executions/{executionId}/variables
----


.为一个执行创建一个新的二进制变量 - URL 参数
[options="header"]
|===============
|参数|必填|值|描述
|executionId|是|String|要创建新变量的执行的id。

|===============


**请求体：**请求需要是++multipart/form-data++类型的。需要有唯一的file-part，包含变量的二进制值。另外，也可以使用下列额外的form-fields：

* ++name++: 变量需要的名字。
* ++type++: 创建的变量的类型。如果忽略，则使用++binary++，并且将请求中的二进制数据保存为字节数组。
* ++scope++: 创建变量的范围。如果忽略，则使用++local++。

**成功响应体：**

[source,json,linenums]
----
{
  "name" : "binaryVariable",
  "scope" : "local",
  "type" : "binary",
  "value" : null,
  "valueUrl" : "http://.../runtime/executions/123/variables/binaryVariable/data"
}
----


.为一个执行创建一个新的二进制变量 - 响应码
[options="header"]
|===============
|响应码|描述
|201|代表已创建变量，并已返回结果。
|400|代表缺少要创建的变量名。状态消息提供了额外信息。
|404|代表未找到请求的执行。
|409|代表执行已包含了给定名字的变量（只在使用POST方法时抛出）。改用PUT方法更新变量方法。
|415|代表序列化数据中包含了一个运行Activiti引擎的JVM中不存在的类的对象，因此不能反序列化。
|===============


==== 为一个执行更新一个已有二进制变量 Update an existing binary variable on a process-instance

----
PUT runtime/executions/{executionId}/variables/{variableName}
----

.为一个执行更新一个已有二进制变量 - URL 参数
[options="header"]
|===============
|参数|必填|值|描述
|executionId|是|String|要更新变量的执行的id。
|variableName|是|String|要更新的变量名。

|===============


**请求体：**请求需要是++multipart/form-data++类型的。需要有唯一的file-part，包含变量的二进制值。另外，也可以使用下列额外的form-fields：

* ++name++: 变量需要的名字。
* ++type++: 创建的变量的类型。如果忽略，则使用++binary++，并且将请求中的二进制数据保存为字节数组。
* ++scope++: 创建变量的范围。如果忽略，则使用++local++。

**成功响应体：**

[source,json,linenums]
----
{
  "name" : "binaryVariable",
  "scope" : "local",
  "type" : "binary",
  "value" : null,
  "valueUrl" : "http://.../runtime/executions/123/variables/binaryVariable/data"
}
----


.为一个执行更新一个已有二进制变量 - 响应码
[options="header"]
|===============
|响应码|描述
|200|代表已更新变量，并已返回结果。
|400|代表缺少要更新的变量名。状态消息提供了额外信息。
|404|代表未找到请求的执行，或者执行中没有给定名字的变量。
|415|代表序列化数据中包含了一个运行Activiti引擎的JVM中不存在的类的对象，因此不能反序列化。

|===============



=== 任务 Tasks


==== 获取一个任务 Get a task

----
GET runtime/tasks/{taskId}
----

.Get a task - URL 参数
[options="header"]
|===============
|参数|必填|值|描述
|taskId|是|String|要获取的任务的id。

|===============



.Get a task - 响应码
[options="header"]
|===============
|响应码|描述
|200|代表已找到并返回了任务。
|404|代表未找到请求的任务。

|===============


**成功响应体：**

[source,json,linenums]
----
{
  "assignee" : "kermit",
  "createTime" : "2013-04-17T10:17:43.902+0000",
  "delegationState" : "pending",
  "description" : "Task description",
  "dueDate" : "2013-04-17T10:17:43.902+0000",
  "execution" : "http://localhost:8182/runtime/executions/5",
  "id" : "8",
  "name" : "My task",
  "owner" : "owner",
  "parentTask" : "http://localhost:8182/runtime/tasks/9",
  "priority" : 50,
  "processDefinition" : "http://localhost:8182/repository/process-definitions/oneTaskProcess%3A1%3A4",
  "processInstance" : "http://localhost:8182/runtime/process-instances/5",
  "suspended" : false,
  "taskDefinitionKey" : "theTask",
  "url" : "http://localhost:8182/runtime/tasks/8",
  "tenantId" : null
}
----


* ++delegationState++: 任务的代理状态，可以为++null++、++"pending"++或++"resolved"++。


[[restTasksGet]]


==== 列表任务 List of tasks

----
GET runtime/tasks
----


.列表任务 - URL 查询参数
[options="header"]
|===============
|参数|必填|值|描述
|name|否|String|只返回给定名字的任务。
|nameLike|否|String|只返回名字like给定名字的任务。
|description|否|String|只返回给定描述的任务。
|priority|否|Integer|只返回给定优先级的任务。
|minimumPriority|否|Integer|只返回优先级高于给定值的任务。
|maximumPriority|否|Integer|只返回优先级低于给定值的任务。
|assignee|否|String|只返回指派至给定用户的任务。
|assigneeLike|否|String|只返回办理人like给定值的任务。
|owner|否|String|只返回属主为给定用户的任务。
|ownerLike|否|String|只返回属主like给定值的任务。
|unassigned|否|Boolean|只返回未指派的任务。如果传递++false++，则忽略本参数。
|delegationState|否|String|只返回给定代理状态的任务。可用值为++pending++与++resolved++。
|candidateUser|否|String|只返回可以被给定用户申领的任务。包括用户为候选人，以及用户所在组为候选组的任务。
|candidateGroup|否|String|只返回可以被给定组中的用户申领的任务。
|candidateGroups|否|String|只返回可以被给定组中的用户申领的任务。逗号分隔值。
|involvedUser|否|String|只返回给定用户参与的任务。
|taskDefinitionKey|否|String|只返回给定任务定义id的任务。
|taskDefinitionKeyLike|否|String|只返回任务定义id like给定值的任务。
|processInstanceId|否|String|只返回给定id流程实例中的任务。
|processInstanceBusinessKey|否|String|只返回给定businessKey流程实例中的任务。
|processInstanceBusinessKeyLike|否|String|只返回businessKey like给定值的流程实例中的任务。
|processDefinitionKey|否|String|只返回给定key的流程定义的流程实例中的任务。
|processDefinitionKeyLike|否|String|只返回key like给定值的流程定义的流程实例中的任务。
|processDefinitionName|否|String|只返回给定名字的流程定义的流程实例中的任务。
|processDefinitionNameLike|否|String|只返回名字like给定值的流程定义的流程实例中的任务。
|executionId|否|String|只返回给定id的执行中的任务。
|createdOn|否|ISO Date|只返回给定日期创建的任务。
|createdBefore|否|ISO Date|只返回给定日期之前创建的任务。
|createdAfter|否|ISO Date|只返回给定日期之后创建的任务。
|dueOn|否|ISO Date|只返回给定日期到期的任务。
|dueBefore|否|ISO Date|只返回给定日期前到期的任务。
|dueAfter|否|ISO Date|只返回给定日期后到期的任务。
|withoutDueDate|否|boolean|只返回没有到期日期的任务。如果值为++false++则忽略本参数。
|excludeSubTasks|否|Boolean|只返回不是另一个任务的子任务的任务。
|active|否|Boolean|如果值为++true++，则只返回未暂停（要么所在流程未暂停，要么根本不在流程中）的任务。如果值为false，则只返回已暂停流程实例中的任务。
|includeTaskLocalVariables|否|Boolean|是否在结果中包含本地变量。
|includeProcessVariables|否|Boolean|是否在结果中包含流程变量。
|tenantId|否|String|只返回给定tenantId的任务。
|tenantIdLike|否|String|只返回tenantId like给定值的任务。
|withoutTenantId|否|Boolean|如果值为++true++，则只返回未设置tenantId的任务。如果值为++false++，则忽略++withoutTenantId++参数。
|candidateOrAssigned|否|String|选择已被申领，或已指派给用户，或等待用户（候选用户或组）申领的任务。

|===============

可以在这个URL中使用通用<<restPagingAndSort,分页与排序查询参数>>。

.列表任务 - 响应码
[options="header"]
|===============
|响应码|描述
|200|代表请求成功，并已返回任务。
|400|代表传递的参数格式错误，或'delegationState'使用了不合法的值（不是'pending'与'resolved'）。状态描述中包含了额外信息。

|===============


**成功响应体：**

[source,json,linenums]
----
{
  "data": [
    {
      "assignee" : "kermit",
      "createTime" : "2013-04-17T10:17:43.902+0000",
      "delegationState" : "pending",
      "description" : "Task description",
      "dueDate" : "2013-04-17T10:17:43.902+0000",
      "execution" : "http://localhost:8182/runtime/executions/5",
      "id" : "8",
      "name" : "My task",
      "owner" : "owner",
      "parentTask" : "http://localhost:8182/runtime/tasks/9",
      "priority" : 50,
      "processDefinition" : "http://localhost:8182/repository/process-definitions/oneTaskProcess%3A1%3A4",
      "processInstance" : "http://localhost:8182/runtime/process-instances/5",
      "suspended" : false,
      "taskDefinitionKey" : "theTask",
      "url" : "http://localhost:8182/runtime/tasks/8",
      "tenantId" : null
    }
  ],
  "total": 1,
  "start": 0,
  "sort": "name",
  "order": "asc",
  "size": 1
}
----



==== 查询任务 Query for tasks

----
POST query/tasks
----


**请求体：**

[source,json,linenums]
----
{
  "name" : "My task",
  "description" : "The task description",

  ...

  "taskVariables" : [
    {
      "name" : "myVariable",
      "value" : 1234,
      "operation" : "equals",
      "type" : "long"
    }
  ],

    "processInstanceVariables" : [
      {
         ...
      }
    ]
  ]
}
----


支持的JSON参数字段与<<restTasksGet,获取任务集合>>的参数一模一样（除了candidateGroupIn，只能在POST任务查询REST服务中使用），但是使用JSON体参数而不是URL参数，可以进行更高级的查询，也可以避免请求URI太长的错误。另外，查询可以通过任务与流程变量进行过滤。++taskVariables++与++processInstanceVariables++都是JSON数组，包含<<restQueryVariable, 这里描述>>的格式的对象。


.查询任务 - 响应码
[options="header"]
|===============
|响应码|描述
|200|代表请求成功，并已返回任务。
|400|代表传递的参数格式错误，或'delegationState'使用了不合法的值（不是'pending'与'resolved'）。状态描述中包含了额外信息。

|===============



**成功响应体：**

[source,json,linenums]
----
{
  "data": [
    {
      "assignee" : "kermit",
      "createTime" : "2013-04-17T10:17:43.902+0000",
      "delegationState" : "pending",
      "description" : "Task description",
      "dueDate" : "2013-04-17T10:17:43.902+0000",
      "execution" : "http://localhost:8182/runtime/executions/5",
      "id" : "8",
      "name" : "My task",
      "owner" : "owner",
      "parentTask" : "http://localhost:8182/runtime/tasks/9",
      "priority" : 50,
      "processDefinition" : "http://localhost:8182/repository/process-definitions/oneTaskProcess%3A1%3A4",
      "processInstance" : "http://localhost:8182/runtime/process-instances/5",
      "suspended" : false,
      "taskDefinitionKey" : "theTask",
      "url" : "http://localhost:8182/runtime/tasks/8",
      "tenantId" : null
    }
  ],
  "total": 1,
  "start": 0,
  "sort": "name",
  "order": "asc",
  "size": 1
}
----


==== 更新一个任务 Update a task


----
PUT runtime/tasks/{taskId}
----


**JSON体：**

[source,json,linenums]
----
{
  "assignee" : "assignee",
  "delegationState" : "resolved",
  "description" : "New task description",
  "dueDate" : "2013-04-17T13:06:02.438+02:00",
  "name" : "New task name",
  "owner" : "owner",
  "parentTaskId" : "3",
  "priority" : 20
}
----

所有的请求值都是可选的。例如，可以只在请求体的JSON对象中包含'assignee'属性，则只更新任务的办理人，而不影响其它所有字段。当显式包含了一个属性，并设置为null，则任务值将更新为null。例如：++{"dueDate" : null}++将清空任务的到期日期。


.更新一个任务 - 响应码
[options="header"]
|===============
|响应码|描述
|200|代表任务已被更新。
|404|代表未找到请求的任务。
|409|代表请求的任务已经被并发同时更新。

|===============


**成功响应体：**参见++runtime/tasks/{taskId}++的响应。


==== 任务操作 Task actions

----
POST runtime/tasks/{taskId}
----

**完成一个任务 - JSON 体:**

[source,json,linenums]
----
{
  "action" : "complete",
  "variables" : []
}
----

完成任务。可以使用++variables++参数传递可选的变量数组。可以在<<restVariables,REST变量章节>>找到关于变量格式的更多信息。请注意提供的变量范围将被忽略，变量将设置在父范围中，除非一个本地范围中存在一个变量。这种情况下将被覆盖。与++TaskService.completeTask(taskId, variables)++调用的行为相同。

**申领一个任务 - JSON 体:**

[source,json,linenums]
----
{
  "action" : "claim",
  "assignee" : "userWhoClaims"
}
----

使用给定办理人申领任务。如果办理人为++null++，则取消任务的指派，可以重新申领。

**代理一个任务 - JSON 体:**

[source,json,linenums]
----
{
  "action" : "delegate",
  "assignee" : "userToDelegateTo"
}
----

将任务代理给给定办理人。办理人为必填。

**解决一个任务 - JSON 体:**

[source,json,linenums]
----

{
  "action" : "resolve"
}
----

解决任务代理。任务指派回任务的属主（若有）。


.任务操作 - 响应码
[options="header"]
|===============
|响应码|描述
|200|代表已执行操作。
|400|代表请求体包含非法值，或者当操作需要时没有提供办理人。
|404|代表未找到请求的任务。
|409|代表操作由于冲突无法执行。任务已被并发同时更新，或者在进行'++claim++'操作时，任务已被其他用户申领。

|===============


**成功响应体：** see response for +runtime/tasks/{taskId}+.


==== 删除一个任务 Delete a task


----
DELETE runtime/tasks/{taskId}?cascadeHistory={cascadeHistory}&deleteReason={deleteReason}
----


.删除一个任务 - URL 参数
[options="header"]
|===============
|参数|必填|值|描述
|taskId|是|String|要删除的任务的id。
|cascadeHistory|否|Boolean|是否在删除任务时，删除历史任务实例（如果可用）。如果未设置，则默认值为false。
|deleteReason|否|String|任务删除的原因。如果++cascadeHistory++值为true，则忽略本参数。

|===============


.删除一个任务 - 响应码
[options="header"]
|===============
|响应码|描述
|204|代表已找到并删除任务。响应体设置为空。
|403|代表由于请求的任务是工作流的一部分，无法删除。
|404|代表未找到请求的任务。

|===============



==== 获取一个任务的所有变量 Get all variables for a task

----
GET runtime/tasks/{taskId}/variables?scope={scope}
----


.获取一个任务的所有变量 - URL 参数
[options="header"]
|===============
|参数|必填|值|描述
|taskId|是|String|要获取变量的任务的id。
|scope|否|String|要返回的变量的范围。若值为'++local++'，则只返回任务本地变量。若值为'++global++'，则只返回任务的父执行树中的变量。若省略该参数，则本地与全局都会返回。

|===============


.获取一个任务的所有变量 - 响应码
[options="header"]
|===============
|响应码|描述
|200|代表已找到任务，并已返回请求的变量。
|404|代表未找到请求的任务。

|===============


**成功响应体：**

[source,json,linenums]
----
[
  {
    "name" : "doubleTaskVar",
    "scope" : "local",
    "type" : "double",
    "value" : 99.99
  },
  {
    "name" : "stringProcVar",
    "scope" : "global",
    "type" : "string",
    "value" : "This is a ProcVariable"
  }



]
----

变量作为一个JSON数组返回。在通用<<restVariables,REST变量章节>>中可以找到全部响应体的描述。


==== 从一个任务中获取一个变量 Get a variable from a task

----
GET runtime/tasks/{taskId}/variables/{variableName}?scope={scope}
----


.从一个任务中获取一个变量 - URL 参数
[options="header"]
|===============
|参数|必填|值|描述
|taskId|是|String|要获取变量的任务的id。
|variableName|是|String|要获取的变量名。
|scope|否|String|要返回的变量的范围。若值为'++local++'，则只返回任务本地变量。若值为'++global++'，则只返回任务的父执行树中的变量。若省略该参数，如果存在本地变量就会返回，否则返回全局变量。

|===============


.从一个任务中获取一个变量 - 响应码
[options="header"]
|===============
|响应码|描述
|200|代表已找到任务，并已返回请求的变量。
|404|代表未找到请求的任务，或者任务（在给定范围中）没有给定名字的变量。状态消息提供了额外信息。

|===============


**成功响应体：**

[source,json,linenums]
----
{
  "name" : "myTaskVariable",
  "scope" : "local",
  "type" : "string",
  "value" : "Hello my friend"
}
----

在通用<<restVariables,REST变量章节>>中可以找到全部响应体的描述。


==== 获取一个变量的二进制数据 Get the binary data for a variable

----
GET runtime/tasks/{taskId}/variables/{variableName}/data?scope={scope}
----


.获取一个变量的二进制数据 - URL 参数
[options="header"]
|===============
|参数|必填|值|描述
|taskId|是|String|要获取变量的任务的id。
|variableName|是|String|要获取数据的变量名。只能使用++binary++与++serializable++类型的变量。如果使用其它任何类型的变量，将返回++404++。
|scope|否|String|要返回的变量的范围。若值为'++local++'，则只返回任务本地变量。若值为'++global++'，则只返回任务的父执行树中的变量。若省略该参数，如果存在本地变量就会返回，否则返回全局变量。

|===============



.获取一个变量的二进制数据 - 响应码
[options="header"]
|===============
|响应码|描述
|200|代表已找到任务，并已返回请求的变量。
|404|代表未找到请求的任务，或者任务（在给定范围中）没有给定名字的变量，或者变量没有可用的二进制流。状态消息提供了额外信息。

|===============



**成功响应体：**响应体包含了变量的二进制值。如果变量是++binary++类型，则不论变量的content或者请求的accept-type头是什么，响应的content-type都将设置为++application/octet-stream++。如果变量是++serializable++类型，则content-type会使用++application/x-java-serialized-object++。



==== 为一个任务创建一个新的变量 Create new variables on a task


----
POST runtime/tasks/{taskId}/variables
----


.为一个任务创建一个新的变量 - URL 参数
[options="header"]
|===============
|参数|必填|值|描述
|taskId|是|String|要创建新变量的任务的id。

|===============

**创建简单（非二进制）变量的请求体：**

[source,json,linenums]
----
[
  {
    "name" : "myTaskVariable",
    "scope" : "local",
    "type" : "string",
    "value" : "Hello my friend"
  },
  {

  }
]
----


请求体需要是一个数组，包含有一个或多个代表要创建的变量JSON对象

* ++name++: 变量需要的名字。
* ++scope++: 创建变量的范围。如果忽略，则使用++local++。
* ++type++: 创建的变量的类型。如果忽略，则转换为原始JSON值的类型（string、boolean、integer或double）。
* ++value++: 变量值。

可以在<<restVariables,REST变量章节>>找到关于变量格式的更多信息。


**成功响应体：**

[source,json,linenums]
----
[
  {
    "name" : "myTaskVariable",
    "scope" : "local",
    "type" : "string",
    "value" : "Hello my friend"
  },
  {

  }
]
----


.为一个任务创建一个新的变量 - 响应码
[options="header"]
|===============
|响应码|描述
|201|代表已创建变量，并已返回结果。
|400|代表缺少要创建的变量名，或者尝试为独立任务（未关联至流程）创建++global++变量，或者请求中包含了空的变量数组，或者请求中没有包含变量数组。状态消息提供了额外信息。
|404|代表未找到请求的任务。
|409|代表任务中已有给定名字的变量。改用PUT方法更新任务变量。

|===============


==== 为一个任务创建一个新的二进制变量 Create a new binary variable on a task

----
POST runtime/tasks/{taskId}/variables
----


.为一个任务创建一个新的二进制变量 - URL 参数
[options="header"]
|===============
|参数|必填|值|描述
|taskId|是|String|要创建新变量的任务的id。

|===============


**请求体：**请求需要是++multipart/form-data++类型的。需要有唯一的file-part，包含变量的二进制值。另外，也可以使用下列额外的form-fields：

* ++name++: 变量需要的名字。
* ++scope++: 创建变量的范围。如果忽略，则使用++local++。
* ++type++: 创建的变量的类型。如果忽略，则使用++binary++，并且将请求中的二进制数据保存为字节数组。


**成功响应体：**

[source,json,linenums]
----
{
  "name" : "binaryVariable",
  "scope" : "local",
  "type" : "binary",
  "value" : null,
  "valueUrl" : "http://.../runtime/tasks/123/variables/binaryVariable/data"
}
----

.为一个任务创建一个新的二进制变量 - 响应码
[options="header"]
|===============
|响应码|描述
|201|代表已创建变量，并已返回结果。
|400|代表缺少要创建的变量名，或者尝试为独立任务（未关联至流程）创建++global++变量。状态消息提供了额外信息。
|404|代表未找到请求的任务。
|409|代表任务中已有给定名字的变量。改用PUT方法更新任务变量。
|415|代表序列化数据中包含了一个运行Activiti引擎的JVM中不存在的类的对象，因此不能反序列化。

|===============



==== 为一个任务更新一个已有变量 Update an existing variable on a task


----
PUT runtime/tasks/{taskId}/variables/{variableName}
----


.为一个任务更新一个已有变量 - URL 参数
[options="header"]
|===============
|参数|必填|值|描述
|taskId|是|String|要更新变量的任务的id。
|variableName|是|String|要更新的变量名。

|===============

**更新简单（非二进制）变量的请求体：**

[source,json,linenums]
----
{
  "name" : "myTaskVariable",
  "scope" : "local",
  "type" : "string",
  "value" : "Hello my friend"
}
----


请求体需要是一个数组，包含有一个或多个代表要创建的变量JSON对象

* ++name++: 变量需要的名字。
* ++scope++: 创建变量的范围。如果忽略，则使用++local++。
* ++type++: 创建的变量的类型。如果忽略，则转换为原始JSON值的类型（string、boolean、integer或double）。
* ++value++: 变量值。

可以在<<restVariables,REST变量章节>>找到关于变量格式的更多信息。

**成功响应体：**

[source,json,linenums]
----
{
  "name" : "myTaskVariable",
  "scope" : "local",
  "type" : "string",
  "value" : "Hello my friend"
}
----


.为一个任务更新一个已有变量 - 响应码
[options="header"]
|===============
|响应码|描述
|200|代表已更新变量，并已返回结果。
|400|代表缺少要创建的变量名，或者尝试为独立任务（未关联至流程）创建++global++变量。状态消息提供了额外信息。
|404|代表未找到请求的任务，或者任务在给定范围中没有给定名字的变量。状态消息提供了额外信息。

|===============



==== 为一个任务更新一个二进制变量 Updating a binary variable on a task

----
PUT runtime/tasks/{taskId}/variables/{variableName}
----

.为一个任务更新一个二进制变量 - URL 参数
[options="header"]
|===============
|参数|必填|值|描述
|taskId|是|String|要更新变量的任务的id。
|variableName|是|String|要更新的变量名。

|===============



**请求体：**请求需要是++multipart/form-data++类型的。需要有唯一的file-part，包含变量的二进制值。另外，也可以使用下列额外的form-fields：

* ++name++: 变量需要的名字。
* ++scope++: 创建变量的范围。如果忽略，则使用++local++。
* ++type++: 创建的变量的类型。如果忽略，则使用++binary++，并且将请求中的二进制数据保存为字节数组。

**成功响应体：**

[source,json,linenums]
----
{
  "name" : "binaryVariable",
  "scope" : "local",
  "type" : "binary",
  "value" : null,
  "valueUrl" : "http://.../runtime/tasks/123/variables/binaryVariable/data"
}
----


.为一个任务更新一个二进制变量 - 响应码
[options="header"]
|===============
|响应码|描述
|200|代表已更新变量，并已返回结果。
|400|代表缺少要创建的变量名，或者尝试为独立任务（未关联至流程）创建++global++变量。状态消息提供了额外信息。
|404|代表未找到请求的任务，或者任务在给定范围中没有给定名字的变量。
|415|代表序列化数据中包含了一个运行Activiti引擎的JVM中不存在的类的对象，因此不能反序列化。

|===============



==== 为一个任务删除一个变量 Delete a variable on a task

----
DELETE runtime/tasks/{taskId}/variables/{variableName}?scope={scope}
----


.为一个任务删除一个变量 - URL 参数
[options="header"]
|===============
|参数|必填|值|描述
|taskId|是|String|要删除的变量所在的任务的id。
|variableName|是|String|要删除的变量名。
|scope|否|String|要删除的变量所在的范围。可以为++local++或++global++。若省略，则使用++local++。

|===============


.为一个任务删除一个变量 - 响应码
[options="header"]
|===============
|响应码|描述
|204|代表已找到并删除任务变量。响应体设置为空。
|404|代表未找到请求的任务，或者任务在给定范围中没有给定名字的变量。状态消息提供了额外信息。

|===============



==== 为一个任务删除所有本地变量 Delete all local variables on a task

----
DELETE runtime/tasks/{taskId}/variables
----

.为一个任务删除所有本地变量 - URL 参数
[options="header"]
|===============
|参数|必填|值|描述
|taskId|是|String|要删除的变量所在的任务的id。

|===============


.为一个任务删除所有本地变量 - 响应码
[options="header"]
|===============
|响应码|描述
|204|代表已删除所有本地任务变量。响应体设置为空。
|404|代表未找到请求的任务。

|===============



==== 获取一个任务的所有身份联系 Get all identity links for a task


----
GET runtime/tasks/{taskId}/identitylinks
----


.获取一个任务的所有身份联系 - URL 参数
[options="header"]
|===============
|参数|必填|值|描述
|taskId|是|String|要获取身份联系的任务的id。

|===============


.获取一个任务的所有身份联系 - 响应码
[options="header"]
|===============
|响应码|描述
|200|代表已找到任务，并已返回请求的身份联系。
|404|代表未找到请求的任务。

|===============


**成功响应体：**

[source,json,linenums]
----
[
  {
    "userId" : "kermit",
    "groupId" : null,
    "type" : "candidate",
    "url" : "http://localhost:8081/activiti-rest/service/runtime/tasks/100/identitylinks/users/kermit/candidate"
  },
  {
    "userId" : null,
    "groupId" : "sales",
    "type" : "candidate",
    "url" : "http://localhost:8081/activiti-rest/service/runtime/tasks/100/identitylinks/groups/sales/candidate"
  },

  ...
]
----



==== 获取一个任务的组或用户的所有身份联系 Get all identitylinks for a task for either groups or users

----
GET runtime/tasks/{taskId}/identitylinks/users
GET runtime/tasks/{taskId}/identitylinks/groups
----

只返回目标为用户或组的身份联系。响应体及状态码与获取一个任务的完整身份联系列表时完全相同。


==== 获取一个任务的一个身份联系 Get a single identity link on a task



----
GET runtime/tasks/{taskId}/identitylinks/{family}/{identityId}/{type}
----


.获取一个任务的一个身份联系 - URL 参数
[options="header"]
|===============
|参数|必填|值|描述
|taskId|是|String|任务的id。
|family|是|String|可以为++groups++或++users++，取决于认证目标的类型。
|identityId|是|String|认证的id。
|type|是|String|身份联系的类型。

|===============


.获取一个任务的一个身份联系 - 响应码
[options="header"]
|===============
|响应码|描述
|200|代表已找到任务及身份联系，并已返回。
|404|代表未找到请求的任务，或者任务中没有请求的身份联系。状态消息提供了额外信息。

|===============


**成功响应体：**

[source,json,linenums]
----
{
  "userId" : null,
  "groupId" : "sales",
  "type" : "candidate",
  "url" : "http://localhost:8081/activiti-rest/service/runtime/tasks/100/identitylinks/groups/sales/candidate"
}
----


==== 为一个任务创建一个身份联系 Create an identity link on a task


----
POST runtime/tasks/{taskId}/identitylinks
----


.Create an identity link on a task - URL 参数
[options="header"]
|===============
|参数|必填|值|描述
|taskId|是|String|The id of the task .

|===============



*Request body (user):*

[source,json,linenums]
----
{
  "userId" : "kermit",
  "type" : "candidate",
}
----


*Request body (group):*

[source,json,linenums]
----
{
  "groupId" : "sales",
  "type" : "candidate",
}
----

.Create an identity link on a task - 响应码
[options="header"]
|===============
|响应码|描述
|201|Indicates the task was found and the identity link was created.
|404|Indicates the requested task was not found or the task doesn't have the requested identityLink. 状态消息提供了额外信息。

|===============



**成功响应体：**

[source,json,linenums]
----
{
  "userId" : null,
  "groupId" : "sales",
  "type" : "candidate",
  "url" : "http://localhost:8081/activiti-rest/service/runtime/tasks/100/identitylinks/groups/sales/candidate"
}
----


==== Delete an identity link on a task

----
DELETE runtime/tasks/{taskId}/identitylinks/{family}/{identityId}/{type}
----

.Delete an identity link on a task - URL 参数
[options="header"]
|===============
|参数|必填|值|描述
|taskId|是|String|The id of the task.
|family|是|String|Either +groups+ or +users+, depending on what kind of identity is targeted.
|identityId|是|String|The id of the identity.
|type|是|String|The type of identity link.

|===============


.Delete an identity link on a task - 响应码
[options="header"]
|===============
|响应码|描述
|204|Indicates the task and identity link were found and the link has been deleted. 响应体设置为空。
|404|Indicates the requested task was not found or the task doesn't have the requested identityLink. 状态消息提供了额外信息。

|===============




==== Create a new comment on a task


----
POST runtime/tasks/{taskId}/comments
----

.Create a new comment on a task - URL 参数
[options="header"]
|===============
|参数|必填|值|描述
|taskId|是|String|The id of the task to create the comment for.

|===============


**请求体：**

[source,json,linenums]
----
{
  "message" : "This is a comment on the task.",
  "saveProcessInstanceId" : true
}
----


Parameter +saveProcessInstanceId+ is optional, if +true+ save process instance id of task with comment.

**成功响应体：**

[source,json,linenums]
----
{
  "id" : "123",
  "taskUrl" : "http://localhost:8081/activiti-rest/service/runtime/tasks/101/comments/123",
  "processInstanceUrl" : "http://localhost:8081/activiti-rest/service/history/historic-process-instances/100/comments/123",
  "message" : "This is a comment on the task.",
  "author" : "kermit",
  "time" : "2014-07-13T13:13:52.232+08:00"
  "taskId" : "101",
  "processInstanceId" : "100"
}
----


.Create a new comment on a task - 响应码
[options="header"]
|===============
|响应码|描述
|201|Indicates the comment was created and the result is returned.
|400|Indicates the comment is missing from the request.
|404|代表未找到请求的任务。

|===============



==== Get all comments on a task

----
GET runtime/tasks/{taskId}/comments
----

.Get all comments on a task - URL 参数
[options="header"]
|===============
|参数|必填|值|描述
|taskId|是|String|The id of the task to get the comments for.

|===============

**成功响应体：**

[source,json,linenums]
----
[
  {
    "id" : "123",
    "taskUrl" : "http://localhost:8081/activiti-rest/service/runtime/tasks/101/comments/123",
    "processInstanceUrl" : "http://localhost:8081/activiti-rest/service/history/historic-process-instances/100/comments/123",
    "message" : "This is a comment on the task.",
    "author" : "kermit"
    "time" : "2014-07-13T13:13:52.232+08:00"
    "taskId" : "101",
    "processInstanceId" : "100"
  },
  {
    "id" : "456",
    "taskUrl" : "http://localhost:8081/activiti-rest/service/runtime/tasks/101/comments/456",
    "processInstanceUrl" : "http://localhost:8081/activiti-rest/service/history/historic-process-instances/100/comments/456",
    "message" : "This is another comment on the task.",
    "author" : "gonzo",
    "time" : "2014-07-13T13:13:52.232+08:00"
    "taskId" : "101",
    "processInstanceId" : "100"
  }
]
----


.Get all comments on a task - 响应码
[options="header"]
|===============
|响应码|描述
|200|Indicates the task was found and the comments are returned.
|404|代表未找到请求的任务。

|===============



==== Get a comment on a task

----
GET runtime/tasks/{taskId}/comments/{commentId}
----


.Get a comment on a task - URL 参数
[options="header"]
|===============
|参数|必填|值|描述
|taskId|是|String|The id of the task to get the comment for.
|commentId|是|String|The id of the comment.

|===============


**成功响应体：**

[source,json,linenums]
----
{
  "id" : "123",
  "taskUrl" : "http://localhost:8081/activiti-rest/service/runtime/tasks/101/comments/123",
  "processInstanceUrl" : "http://localhost:8081/activiti-rest/service/history/historic-process-instances/100/comments/123",
  "message" : "This is a comment on the task.",
  "author" : "kermit",
  "time" : "2014-07-13T13:13:52.232+08:00"
  "taskId" : "101",
  "processInstanceId" : "100"
}
----

.Get a comment on a task - 响应码
[options="header"]
|===============
|响应码|描述
|200|Indicates the task and comment were found and the comment is returned.
|404|Indicates the requested task was not found or the tasks doesn't have a comment with the given ID.

|===============


==== Delete a comment on a task

----
DELETE runtime/tasks/{taskId}/comments/{commentId}
----

.Delete a comment on a task - URL 参数
[options="header"]
|===============
|参数|必填|值|描述
|taskId|是|String|The id of the task to delete the comment for.
|commentId|是|String|The id of the comment.

|===============


.Delete a comment on a task - 响应码
[options="header"]
|===============
|响应码|描述
|204|Indicates the task and comment were found and the comment is deleted. 响应体设置为空
|404|Indicates the requested task was not found or the tasks doesn't have a comment with the given ID.

|===============


==== Get all events for a task

----
GET runtime/tasks/{taskId}/events
----

.Get all events for a task - URL 参数
[options="header"]
|===============
|参数|必填|值|描述
|taskId|是|String|The id of the task to get the events for.

|===============


**成功响应体：**

[source,json,linenums]
----
[
  {
    "action" : "AddUserLink",
    "id" : "4",
    "message" : [ "gonzo", "contributor" ],
    "taskUrl" : "http://localhost:8182/runtime/tasks/2",
    "time" : "2013-05-17T11:50:50.000+0000",
    "url" : "http://localhost:8182/runtime/tasks/2/events/4",
    "userId" : null
  }

]
----


.Get all events for a task - 响应码
[options="header"]
|===============
|响应码|描述
|200|Indicates the task was found and the events are returned.
|404|代表未找到请求的任务。

|===============



==== Get an event on a task

----
GET runtime/tasks/{taskId}/events/{eventId}
----

.Get an event on a task - URL 参数
[options="header"]
|===============
|参数|必填|值|描述
|taskId|是|String|The id of the task to get the event for.
|eventId|是|String|The id of the event.

|===============



**成功响应体：**

[source,json,linenums]
----
{
  "action" : "AddUserLink",
  "id" : "4",
  "message" : [ "gonzo", "contributor" ],
  "taskUrl" : "http://localhost:8182/runtime/tasks/2",
  "time" : "2013-05-17T11:50:50.000+0000",
  "url" : "http://localhost:8182/runtime/tasks/2/events/4",
  "userId" : null
}
----


.Get an event on a task - 响应码
[options="header"]
|===============
|响应码|描述
|200|Indicates the task and event were found and the event is returned.
|404|Indicates the requested task was not found or the tasks doesn't have an event with the given ID.

|===============



==== Create a new attachment on a task, containing a link to an external resource

----
POST runtime/tasks/{taskId}/attachments
----

.Create a new attachment on a task, containing a link to an external resource - URL 参数
[options="header"]
|===============
|参数|必填|值|描述
|taskId|是|String|The id of the task to create the attachment for.

|===============


**请求体：**

[source,json,linenums]
----
{
  "name":"Simple attachment",
  "description":"Simple attachment description",
  "type":"simpleType",
  "externalUrl":"http://activiti.org"
}
----


Only the attachment name is required to create a new attachment.



**成功响应体：**

[source,json,linenums]
----
{
  "id":"3",
  "url":"http://localhost:8182/runtime/tasks/2/attachments/3",
  "name":"Simple attachment",
  "description":"Simple attachment description",
  "type":"simpleType",
  "taskUrl":"http://localhost:8182/runtime/tasks/2",
  "processInstanceUrl":null,
  "externalUrl":"http://activiti.org",
  "contentUrl":null
}
----


.Create a new attachment on a task, containing a link to an external resource - 响应码
[options="header"]
|===============
|响应码|描述
|201|Indicates the attachment was created and the result is returned.
|400|Indicates the attachment name is missing from the request.
|404|代表未找到请求的任务。

|===============



==== Create a new attachment on a task, with an attached file

----
POST runtime/tasks/{taskId}/attachments
----

.Create a new attachment on a task, with an attached file - URL 参数
[options="header"]
|===============
|参数|必填|值|描述
|taskId|是|String|The id of the task to create the attachment for.

|===============


**请求体：**

The request should be of type +multipart/form-data+. There should be a single file-part included with the binary value of the variable. On top of that, the following additional form-fields can be present:

* ++name++: Required name of the variable.
* ++description++: Description of the attachment, optional.
* ++type++: Type of attachment, optional. Supports any arbitrary string or a valid HTTP content-type.

**成功响应体：**

[source,json,linenums]
----
{
	"id":"5",
	"url":"http://localhost:8182/runtime/tasks/2/attachments/5",
    "name":"Binary attachment",
    "description":"Binary attachment description",
    "type":"binaryType",
    "taskUrl":"http://localhost:8182/runtime/tasks/2",
    "processInstanceUrl":null,
    "externalUrl":null,
    "contentUrl":"http://localhost:8182/runtime/tasks/2/attachments/5/content"
}
----


.Create a new attachment on a task, with an attached file - 响应码
[options="header"]
|===============
|响应码|描述
|201|Indicates the attachment was created and the result is returned.
|400|Indicates the attachment name is missing from the request or no file was present in the request. The error-message contains additional information.
|404|代表未找到请求的任务。

|===============


==== Get all attachments on a task

----
GET runtime/tasks/{taskId}/attachments
----


.Get all attachments on a task - URL 参数
[options="header"]
|===============
|参数|必填|值|描述
|taskId|是|String|The id of the task to get the attachments for.

|===============


**成功响应体：**

[source,json,linenums]
----
[
  {
    "id":"3",
    "url":"http://localhost:8182/runtime/tasks/2/attachments/3",
    "name":"Simple attachment",
    "description":"Simple attachment description",
    "type":"simpleType",
    "taskUrl":"http://localhost:8182/runtime/tasks/2",
    "processInstanceUrl":null,
    "externalUrl":"http://activiti.org",
    "contentUrl":null
  },
  {
    "id":"5",
    "url":"http://localhost:8182/runtime/tasks/2/attachments/5",
    "name":"Binary attachment",
    "description":"Binary attachment description",
    "type":"binaryType",
    "taskUrl":"http://localhost:8182/runtime/tasks/2",
    "processInstanceUrl":null,
    "externalUrl":null,
    "contentUrl":"http://localhost:8182/runtime/tasks/2/attachments/5/content"
  }
]
----


.Get all attachments on a task - 响应码
[options="header"]
|===============
|响应码|描述
|200|Indicates the task was found and the attachments are returned.
|404|代表未找到请求的任务。

|===============




==== Get an attachment on a task

----
GET runtime/tasks/{taskId}/attachments/{attachmentId}
----

.Get an attachment on a task - URL 参数
[options="header"]
|===============
|参数|必填|值|描述
|taskId|是|String|The id of the task to get the attachment for.
|attachmentId|是|String|The id of the attachment.

|===============


**成功响应体：**

[source,json,linenums]
----
{
  "id":"5",
  "url":"http://localhost:8182/runtime/tasks/2/attachments/5",
  "name":"Binary attachment",
  "description":"Binary attachment description",
  "type":"binaryType",
  "taskUrl":"http://localhost:8182/runtime/tasks/2",
  "processInstanceUrl":null,
  "externalUrl":null,
  "contentUrl":"http://localhost:8182/runtime/tasks/2/attachments/5/content"
}
----


*  ++externalUrl - contentUrl:++In case the attachment is a link to an external resource, the +externalUrl+ contains the URL to the external content. If the attachment content is present in the Activiti engine, the +contentUrl+ will contain an URL where the binary content can be streamed from.
*  ++type:++Can be any arbitrary value. When a valid formatted media-type (e.g. application/xml, text/plain) is included, the binary content HTTP response content-type will be set the the given value.

.Get an attachment on a task - 响应码
[options="header"]
|===============
|响应码|描述
|200|Indicates the task and attachment were found and the attachment is returned.
|404|Indicates the requested task was not found or the tasks doesn't have a attachment with the given ID.

|===============



==== Get the content for an attachment


----
GET runtime/tasks/{taskId}/attachment/{attachmentId}/content
----

.Get the content for an attachment - URL 参数
[options="header"]
|===============
|参数|必填|值|描述
|taskId|是|String|The id of the task to get a variable data for.
|attachmentId|是|String|The id of the attachment, a +404+ is returned when the attachment points to an external URL rather than content attached in Activiti.

|===============


.Get the content for an attachment - 响应码
[options="header"]
|===============
|响应码|描述
|200|Indicates the task and attachment was found and the requested content is returned.
|404|Indicates the requested task was not found or the task doesn't have an attachment with the given id or the attachment doesn't have a binary stream available. 状态消息提供了额外信息。

|===============


**成功响应体：**

The response body contains the binary content. By default, the content-type of the response is set to +application/octet-stream+ unless the attachment type contains a valid Content-type.


==== Delete an attachment on a task


----
DELETE runtime/tasks/{taskId}/attachments/{attachmentId}
----

.Delete an attachment on a task - URL 参数
[options="header"]
|===============
|参数|必填|值|描述
|taskId|是|String|The id of the task to delete the attachment for.
|attachmentId|是|String|The id of the attachment.

|===============


.Delete an attachment on a task - 响应码
[options="header"]
|===============
|响应码|描述
|204|Indicates the task and attachment were found and the attachment is deleted. 响应体设置为空
|404|Indicates the requested task was not found or the tasks doesn't have a attachment with the given ID.

|===============


=== History

==== Get a historic process instance


----
GET history/historic-process-instances/{processInstanceId}
----

.Get a historic process instance - 响应码
[options="header"]
|===============
|响应码|描述
|200|Indicates that the historic process instances could be found.
|404|Indicates that the historic process instances could not be found.

|===============


**成功响应体：**

[source,json,linenums]
----
{
  "data": [
    {
      "id" : "5",
      "businessKey" : "myKey",
      "processDefinitionId" : "oneTaskProcess%3A1%3A4",
      "processDefinitionUrl" : "http://localhost:8182/repository/process-definitions/oneTaskProcess%3A1%3A4",
      "startTime" : "2013-04-17T10:17:43.902+0000",
      "endTime" : "2013-04-18T14:06:32.715+0000",
      "durationInMillis" : 86400056,
      "startUserId" : "kermit",
      "startActivityId" : "startEvent",
      "endActivityId" : "endEvent",
      "deleteReason" : null,
      "superProcessInstanceId" : "3",
      "url" : "http://localhost:8182/history/historic-process-instances/5",
      "variables": null,
      "tenantId":null
    }
  ],
  "total": 1,
  "start": 0,
  "sort": "name",
  "order": "asc",
  "size": 1
}
----


[[restHistoricProcessInstancesGet]]


==== List of historic process instances

----
GET history/historic-process-instances
----

.List of historic process instances - URL 参数
[options="header"]
|===============
|参数|必填|值|描述
|processInstanceId|否|String|An id of the historic process instance.
|processDefinitionKey|否|String|The process definition key of the historic process instance.
|processDefinitionId|否|String|The process definition id of the historic process instance.
|businessKey|否|String|The business key of the historic process instance.
|involvedUser|否|String|An involved user of the historic process instance.
|finished|否|Boolean|Indication if the historic process instance is finished.
|superProcessInstanceId|否|String|An optional parent process id of the historic process instance.
|excludeSubprocesses|否|Boolean|Return only historic process instances which aren't sub processes.
|finishedAfter|否|Date|Return only historic process instances that were finished after this date.
|finishedBefore|否|Date|Return only historic process instances that were finished before this date.
|startedAfter|否|Date|Return only historic process instances that were started after this date.
|startedBefore|否|Date|Return only historic process instances that were started before this date.
|startedBy|否|String|Return only historic process instances that were started by this user.
|includeProcessVariables|否|Boolean|An indication if the historic process instance variables should be returned as well.
|tenantId|否|String|Only return instances with the given tenantId.
|tenantIdLike|否|String|Only return instances with a tenantId like the given value.
|withoutTenantId|否|Boolean|If +true+, only returns instances without a tenantId set. 如果值为++false++，则忽略++withoutTenantId++参数。
|可以在这个URL中使用通用<<restPagingAndSort,分页与排序查询参数>>。

|===============


.List of historic process instances - 响应码
[options="header"]
|===============
|响应码|描述
|200|Indicates that historic process instances could be queried.
|400|Indicates an parameter was passed in the wrong format. 状态描述中包含了额外信息。

|===============


**成功响应体：**

[source,json,linenums]
----
{
  "data": [
    {
      "id" : "5",
      "businessKey" : "myKey",
      "processDefinitionId" : "oneTaskProcess%3A1%3A4",
      "processDefinitionUrl" : "http://localhost:8182/repository/process-definitions/oneTaskProcess%3A1%3A4",
      "startTime" : "2013-04-17T10:17:43.902+0000",
      "endTime" : "2013-04-18T14:06:32.715+0000",
      "durationInMillis" : 86400056,
      "startUserId" : "kermit",
      "startActivityId" : "startEvent",
      "endActivityId" : "endEvent",
      "deleteReason" : null,
      "superProcessInstanceId" : "3",
      "url" : "http://localhost:8182/history/historic-process-instances/5",
      "variables": [
        {
          "name": "test",
          "variableScope": "local",
          "value": "myTest"
        }
      ],
      "tenantId":null
    }
  ],
  "total": 1,
  "start": 0,
  "sort": "name",
  "order": "asc",
  "size": 1
}
----


==== Query for historic process instances

----
POST query/historic-process-instances
----

**请求体：**

[source,json,linenums]
----
{
  "processDefinitionId" : "oneTaskProcess%3A1%3A4",


  "variables" : [
    {
      "name" : "myVariable",
      "value" : 1234,
      "operation" : "equals",
      "type" : "long"
    }
  ]
}
----

All supported JSON parameter fields allowed are exactly the same as the parameters found for <<restHistoricProcessInstancesGet,getting a collection of historic process instances>>, but passed in as JSON-body arguments rather than URL-parameters to allow for more advanced querying and preventing errors with request-uri's that are too long. On top of that, the query allows for filtering based on process variables. The +variables+ property is a JSON-array containing objects with the format <<restQueryVariable, as described here.>>


.Query for historic process instances - 响应码
[options="header"]
|===============
|响应码|描述
|200|Indicates request was successful and the tasks are returned
|400|Indicates an parameter was passed in the wrong format. 状态描述中包含了额外信息。

|===============


**成功响应体：**

[source,json,linenums]
----
{
  "data": [
    {
      "id" : "5",
      "businessKey" : "myKey",
      "processDefinitionId" : "oneTaskProcess%3A1%3A4",
      "processDefinitionUrl" : "http://localhost:8182/repository/process-definitions/oneTaskProcess%3A1%3A4",
      "startTime" : "2013-04-17T10:17:43.902+0000",
      "endTime" : "2013-04-18T14:06:32.715+0000",
      "durationInMillis" : 86400056,
      "startUserId" : "kermit",
      "startActivityId" : "startEvent",
      "endActivityId" : "endEvent",
      "deleteReason" : null,
      "superProcessInstanceId" : "3",
      "url" : "http://localhost:8182/history/historic-process-instances/5",
      "variables": [
        {
          "name": "test",
          "variableScope": "local",
          "value": "myTest"
        }
      ],
      "tenantId":null
    }
  ],
  "total": 1,
  "start": 0,
  "sort": "name",
  "order": "asc",
  "size": 1
}
----


==== Delete a historic process instance

----
DELETE history/historic-process-instances/{processInstanceId}
----


.Response codes
[options="header"]
|===============
|响应码|描述
|200|Indicates that the historic process instance was deleted.
|404|Indicates that the historic process instance could not be found.

|===============


==== Get the identity links of a historic process instance


----
GET history/historic-process-instance/{processInstanceId}/identitylinks
----


.Response codes
[options="header"]
|===============
|响应码|描述
|200|Indicates request was successful and the identity links are returned
|404|Indicates the process instance could not be found.

|===============


**成功响应体：**

[source,json,linenums]
----
[
 {
  "type" : "participant",
  "userId" : "kermit",
  "groupId" : null,
  "taskId" : null,
  "taskUrl" : null,
  "processInstanceId" : "5",
  "processInstanceUrl" : "http://localhost:8182/history/historic-process-instances/5"
 }
]
----



==== Get the binary data for a historic process instance variable

----
GET history/historic-process-instances/{processInstanceId}/variables/{variableName}/data
----


.Get the binary data for a historic process instance variable - 响应码
[options="header"]
|===============
|响应码|描述
|200|Indicates the process instance was found and the requested variable data is returned.
|404|Indicates the requested process instance was not found or the process instance doesn't have a variable with the given name or the variable doesn't have a binary stream available. 状态消息提供了额外信息。

|===============


**成功响应体：**

The response body contains the binary value of the variable. When the variable is of type +binary+, the content-type of the response is set to +application/octet-stream+, regardless of the content of the variable or the request accept-type header. In case of +serializable+, +application/x-java-serialized-object+ is used as content-type.


==== Create a new comment on a historic process instance

----
POST history/historic-process-instances/{processInstanceId}/comments
----


.Create a new comment on a historic process instance - URL 参数
[options="header"]
|===============
|参数|必填|值|描述
|processInstanceId|是|String|The id of the process instance to create the comment for.

|===============


**请求体：**

[source,json,linenums]
----
{
  "message" : "This is a comment.",
  "saveProcessInstanceId" : true
}
----

Parameter +saveProcessInstanceId+ is optional, if +true+ save process instance id of task with comment.

**成功响应体：**

[source,json,linenums]
----
{
  "id" : "123",
  "taskUrl" : "http://localhost:8081/activiti-rest/service/runtime/tasks/101/comments/123",
  "processInstanceUrl" : "http://localhost:8081/activiti-rest/service/history/historic-process-instances/100/comments/123",
  "message" : "This is a comment on the task.",
  "author" : "kermit",
  "time" : "2014-07-13T13:13:52.232+08:00",
  "taskId" : "101",
  "processInstanceId" : "100"
}
----


.Create a new comment on a historic process instance - 响应码
[options="header"]
|===============
|响应码|描述
|201|Indicates the comment was created and the result is returned.
|400|Indicates the comment is missing from the request.
|404|Indicates the requested historic process instance was not found.

|===============



==== Get all comments on a historic process instance


----
GET history/historic-process-instances/{processInstanceId}/comments
----


.Get all comments on a process instance - URL 参数
[options="header"]
|===============
|参数|必填|值|描述
|processInstanceId|是|String|The id of the process instance to get the comments for.

|===============

**成功响应体：**

[source,json,linenums]
----
[
  {
    "id" : "123",
    "processInstanceUrl" : "http://localhost:8081/activiti-rest/service/history/historic-process-instances/100/comments/123",
    "message" : "This is a comment on the task.",
    "author" : "kermit",
    "time" : "2014-07-13T13:13:52.232+08:00",
    "processInstanceId" : "100"
  },
  {
    "id" : "456",
    "processInstanceUrl" : "http://localhost:8081/activiti-rest/service/history/historic-process-instances/100/comments/456",
    "message" : "This is another comment.",
    "author" : "gonzo",
    "time" : "2014-07-14T15:16:52.232+08:00",
    "processInstanceId" : "100"
  }
]
----


.Get all comments on a process instance - 响应码
[options="header"]
|===============
|响应码|描述
|200|Indicates the process instance was found and the comments are returned.
|404|代表未找到请求的任务。

|===============


==== Get a comment on a historic process instance

----
GET history/historic-process-instances/{processInstanceId}/comments/{commentId}
----


.Get a comment on a historic process instance - URL 参数
[options="header"]
|===============
|参数|必填|值|描述
|processInstanceId|是|String|The id of the historic process instance to get the comment for.
|commentId|是|String|The id of the comment.

|===============


**成功响应体：**

[source,json,linenums]
----
{
  "id" : "123",
  "processInstanceUrl" : "http://localhost:8081/activiti-rest/service/history/historic-process-instances/100/comments/456",
  "message" : "This is another comment.",
  "author" : "gonzo",
  "time" : "2014-07-14T15:16:52.232+08:00",
  "processInstanceId" : "100"
}
----


.Get a comment on a historic process instance - 响应码
[options="header"]
|===============
|响应码|描述
|200|Indicates the historic process instance and comment were found and the comment is returned.
|404|Indicates the requested historic process instance was not found or the historic process instance doesn't have a comment with the given ID.

|===============



==== Delete a comment on a historic process instance

----
DELETE history/historic-process-instances/{processInstanceId}/comments/{commentId}
----

.Delete a comment on a historic process instance - URL 参数
[options="header"]
|===============
|参数|必填|值|描述
|processInstanceId|是|String|The id of the historic process instance to delete the comment for.
|commentId|是|String|The id of the comment.

|===============


.Delete a comment on a historic process instance - 响应码
[options="header"]
|===============
|响应码|描述
|204|Indicates the historic process instance and comment were found and the comment is deleted. 响应体设置为空
|404|Indicates the requested task was not found or the historic process instance doesn't have a comment with the given ID.

|===============


==== Get a single historic task instance

----
GET history/historic-task-instances/{taskId}
----

.Get a single historic task instance - 响应码
[options="header"]
|===============
|响应码|描述
|200|Indicates that the historic task instances could be found.
|404|Indicates that the historic task instances could not be found.

|===============


**成功响应体：**

[source,json,linenums]
----
{
  "id" : "5",
  "processDefinitionId" : "oneTaskProcess%3A1%3A4",
  "processDefinitionUrl" : "http://localhost:8182/repository/process-definitions/oneTaskProcess%3A1%3A4",
  "processInstanceId" : "3",
  "processInstanceUrl" : "http://localhost:8182/history/historic-process-instances/3",
  "executionId" : "4",
  "name" : "My task name",
  "description" : "My task description",
  "deleteReason" : null,
  "owner" : "kermit",
  "assignee" : "fozzie",
  "startTime" : "2013-04-17T10:17:43.902+0000",
  "endTime" : "2013-04-18T14:06:32.715+0000",
  "durationInMillis" : 86400056,
  "workTimeInMillis" : 234890,
  "claimTime" : "2013-04-18T11:01:54.715+0000",
  "taskDefinitionKey" : "taskKey",
  "formKey" : null,
  "priority" : 50,
  "dueDate" : "2013-04-20T12:11:13.134+0000",
  "parentTaskId" : null,
  "url" : "http://localhost:8182/history/historic-task-instances/5",
  "variables": null,
  "tenantId":null
}
----


[[restHistoricTaskInstancesGet]]


==== Get historic task instances

----
GET history/historic-task-instances
----


.Get historic task instances - URL 参数
[options="header"]
|===============
|参数|必填|值|描述
|taskId|否|String|An id of the historic task instance.
|processInstanceId|否|String|The process instance id of the historic task instance.
|processDefinitionKey|否|String|The process definition key of the historic task instance.
|processDefinitionKeyLike|否|String|The process definition key of the historic task instance, which matches the given value.
|processDefinitionId|否|String|The process definition id of the historic task instance.
|processDefinitionName|否|String|The process definition name of the historic task instance.
|processDefinitionNameLike|否|String|The process definition name of the historic task instance, which matches the given value.
|processBusinessKey|否|String|The process instance business key of the historic task instance.
|processBusinessKeyLike|否|String|The process instance business key of the historic task instance that matches the given value.
|executionId|否|String|The execution id of the historic task instance.
|taskDefinitionKey|否|String|The task definition key for tasks part of a process
|taskName|否|String|The task name of the historic task instance.
|taskNameLike|否|String|The task name with 'like' operator for the historic task instance.
|taskDescription|否|String|The task description of the historic task instance.
|taskDescriptionLike|否|String|The task description with 'like' operator for the historic task instance.
|taskDefinitionKey|否|String|The task identifier from the process definition for the historic task instance.
|taskDeleteReason|否|String|The task delete reason of the historic task instance.
|taskDeleteReasonLike|否|String|The task delete reason with 'like' operator for the historic task instance.
|taskAssignee|否|String|The assignee of the historic task instance.
|taskAssigneeLike|否|String|The assignee with 'like' operator for the historic task instance.
|taskOwner|否|String|The owner of the historic task instance.
|taskOwnerLike|否|String|The owner with 'like' operator for the historic task instance.
|taskInvolvedUser|否|String|An involved user of the historic task instance.
|taskPriority|否|String|The priority of the historic task instance.
|finished|否|Boolean|Indication if the historic task instance is finished.
|processFinished|否|Boolean|Indication if the process instance of the historic task instance is finished.
|parentTaskId|否|String|An optional parent task id of the historic task instance.
|dueDate|否|Date|Return only historic task instances that have a due date equal this date.
|dueDateAfter|否|Date|Return only historic task instances that have a due date after this date.
|dueDateBefore|否|Date|Return only historic task instances that have a due date before this date.
|withoutDueDate|否|Boolean|Return only historic task instances that have no due-date. When +false+ is provided as value, this parameter is ignored.
|taskCompletedOn|否|Date|Return only historic task instances that have been completed on this date.
|taskCompletedAfter|否|Date|Return only historic task instances that have been completed after this date.
|taskCompletedBefore|否|Date|Return only historic task instances that have been completed before this date.
|taskCreatedOn|否|Date|Return only historic task instances that were created on this date.
|taskCreatedBefore|否|Date|Return only historic task instances that were created before this date.
|taskCreatedAfter|否|Date|Return only historic task instances that were created after this date.
|includeTaskLocalVariables|否|Boolean|An indication if the historic task instance local variables should be returned as well.
|includeProcessVariables|否|Boolean|An indication if the historic task instance global variables should be returned as well.
|tenantId|否|String|Only return historic task instances with the given tenantId.
|tenantIdLike|否|String|Only return historic task instances with a tenantId like the given value.
|withoutTenantId|否|Boolean|If +true+, only returns historic task instances without a tenantId set. 如果值为++false++，则忽略++withoutTenantId++参数。
|可以在这个URL中使用通用<<restPagingAndSort,分页与排序查询参数>>。

|===============


.Get historic task instances - 响应码
[options="header"]
|===============
|响应码|描述
|200|Indicates that historic process instances could be queried.
|400|Indicates an parameter was passed in the wrong format. 状态描述中包含了额外信息。

|===============


**成功响应体：**

[source,json,linenums]
----
{
  "data": [
    {
      "id" : "5",
      "processDefinitionId" : "oneTaskProcess%3A1%3A4",
      "processDefinitionUrl" : "http://localhost:8182/repository/process-definitions/oneTaskProcess%3A1%3A4",
      "processInstanceId" : "3",
      "processInstanceUrl" : "http://localhost:8182/history/historic-process-instances/3",
      "executionId" : "4",
      "name" : "My task name",
      "description" : "My task description",
      "deleteReason" : null,
      "owner" : "kermit",
      "assignee" : "fozzie",
      "startTime" : "2013-04-17T10:17:43.902+0000",
      "endTime" : "2013-04-18T14:06:32.715+0000",
      "durationInMillis" : 86400056,
      "workTimeInMillis" : 234890,
      "claimTime" : "2013-04-18T11:01:54.715+0000",
      "taskDefinitionKey" : "taskKey",
      "formKey" : null,
      "priority" : 50,
      "dueDate" : "2013-04-20T12:11:13.134+0000",
      "parentTaskId" : null,
      "url" : "http://localhost:8182/history/historic-task-instances/5",
      "taskVariables": [
        {
          "name": "test",
          "variableScope": "local",
          "value": "myTest"
        }
      ],
      "processVariables": [
        {
          "name": "processTest",
          "variableScope": "global",
          "value": "myProcessTest"
        }
      ],
      "tenantId":null
    }
  ],
  "total": 1,
  "start": 0,
  "sort": "name",
  "order": "asc",
  "size": 1
}
----


==== Query for historic task instances

----
POST query/historic-task-instances
----


*Query for historic task instances - Request body:*

[source,json,linenums]
----
{
  "processDefinitionId" : "oneTaskProcess%3A1%3A4",
  ...

  "variables" : [
    {
      "name" : "myVariable",
      "value" : 1234,
      "operation" : "equals",
      "type" : "long"
    }
  ]
}
----


All supported JSON parameter fields allowed are exactly the same as the parameters found for <<restHistoricTaskInstancesGet,getting a collection of historic task instances>>, but passed in as JSON-body arguments rather than URL-parameters to allow for more advanced querying and preventing errors with request-uri's that are too long. On top of that, the query allows for filtering based on process variables. The +taskVariables+ and +processVariables+ properties are JSON-arrays containing objects with the format <<restQueryVariable, as described here.>>

.Query for historic task instances - 响应码
[options="header"]
|===============
|响应码|描述
|200|Indicates request was successful and the tasks are returned
|400|Indicates an parameter was passed in the wrong format. 状态描述中包含了额外信息。

|===============


**成功响应体：**

[source,json,linenums]
----
{
  "data": [
    {
      "id" : "5",
      "processDefinitionId" : "oneTaskProcess%3A1%3A4",
      "processDefinitionUrl" : "http://localhost:8182/repository/process-definitions/oneTaskProcess%3A1%3A4",
      "processInstanceId" : "3",
      "processInstanceUrl" : "http://localhost:8182/history/historic-process-instances/3",
      "executionId" : "4",
      "name" : "My task name",
      "description" : "My task description",
      "deleteReason" : null,
      "owner" : "kermit",
      "assignee" : "fozzie",
      "startTime" : "2013-04-17T10:17:43.902+0000",
      "endTime" : "2013-04-18T14:06:32.715+0000",
      "durationInMillis" : 86400056,
      "workTimeInMillis" : 234890,
      "claimTime" : "2013-04-18T11:01:54.715+0000",
      "taskDefinitionKey" : "taskKey",
      "formKey" : null,
      "priority" : 50,
      "dueDate" : "2013-04-20T12:11:13.134+0000",
      "parentTaskId" : null,
      "url" : "http://localhost:8182/history/historic-task-instances/5",
      "taskVariables": [
        {
          "name": "test",
          "variableScope": "local",
          "value": "myTest"
        }
      ],
      "processVariables": [
        {
          "name": "processTest",
          "variableScope": "global",
          "value": "myProcessTest"
        }
      ],
      "tenantId":null
    }
  ],
  "total": 1,
  "start": 0,
  "sort": "name",
  "order": "asc",
  "size": 1
}
----


==== Delete a historic task instance

----
DELETE history/historic-task-instances/{taskId}
----

.Response codes
[options="header"]
|===============
|响应码|描述
|200|Indicates that the historic task instance was deleted.
|404|Indicates that the historic task instance could not be found.

|===============



==== Get the identity links of a historic task instance

----
GET history/historic-task-instance/{taskId}/identitylinks
----

.Response codes
[options="header"]
|===============
|响应码|描述
|200|Indicates request was successful and the identity links are returned
|404|Indicates the task instance could not be found.

|===============


**成功响应体：**

[source,json,linenums]
----
[
 {
  "type" : "assignee",
  "userId" : "kermit",
  "groupId" : null,
  "taskId" : "6",
  "taskUrl" : "http://localhost:8182/history/historic-task-instances/5",
  "processInstanceId" : null,
  "processInstanceUrl" : null
 }
]
----


==== Get the binary data for a historic task instance variable

----
GET history/historic-task-instances/{taskId}/variables/{variableName}/data
----

.Get the binary data for a historic task instance variable - 响应码
[options="header"]
|===============
|响应码|描述
|200|Indicates the task instance was found and the requested variable data is returned.
|404|Indicates the requested task instance was not found or the process instance doesn't have a variable with the given name or the variable doesn't have a binary stream available. 状态消息提供了额外信息。

|===============


**成功响应体：**

The response body contains the binary value of the variable. When the variable is of type +binary+, the content-type of the response is set to +application/octet-stream+, regardless of the content of the variable or the request accept-type header. In case of +serializable+, +application/x-java-serialized-object+ is used as content-type.


[[restHistoricActivityInstancesGet]]


==== Get historic activity instances

----
GET history/historic-activity-instances
----

.Get historic activity instances - URL 参数
[options="header"]
|===============
|参数|必填|值|描述
|activityId|否|String|An id of the activity instance.
|activityInstanceId|否|String|An id of the historic activity instance.
|activityName|否|String|The name of the historic activity instance.
|activityType|否|String|The element type of the historic activity instance.
|executionId|否|String|The execution id of the historic activity instance.
|finished|否|Boolean|Indication if the historic activity instance is finished.
|taskAssignee|否|String|The assignee of the historic activity instance.
|processInstanceId|否|String|The process instance id of the historic activity instance.
|processDefinitionId|否|String|The process definition id of the historic activity instance.
|tenantId|否|String|Only return instances with the given tenantId.
|tenantIdLike|否|String|Only return instances with a tenantId like the given value.
|withoutTenantId|否|Boolean|If +true+, only returns instances without a tenantId set. 如果值为++false++，则忽略++withoutTenantId++参数。
|可以在这个URL中使用通用<<restPagingAndSort,分页与排序查询参数>>。

|===============



.Get historic activity instances - 响应码
[options="header"]
|===============
|响应码|描述
|200|Indicates that historic activity instances could be queried.
|400|Indicates an parameter was passed in the wrong format. 状态描述中包含了额外信息。

|===============



**成功响应体：**

[source,json,linenums]
----
{
  "data": [
    {
      "id" : "5",
      "activityId" : "4",
      "activityName" : "My user task",
      "activityType" : "userTask",
      "processDefinitionId" : "oneTaskProcess%3A1%3A4",
      "processDefinitionUrl" : "http://localhost:8182/repository/process-definitions/oneTaskProcess%3A1%3A4",
      "processInstanceId" : "3",
      "processInstanceUrl" : "http://localhost:8182/history/historic-process-instances/3",
      "executionId" : "4",
      "taskId" : "4",
      "calledProcessInstanceId" : null,
      "assignee" : "fozzie",
      "startTime" : "2013-04-17T10:17:43.902+0000",
      "endTime" : "2013-04-18T14:06:32.715+0000",
      "durationInMillis" : 86400056,
      "tenantId":null
    }
  ],
  "total": 1,
  "start": 0,
  "sort": "name",
  "order": "asc",
  "size": 1
}
----


==== Query for historic activity instances

----
POST query/historic-activity-instances
----


**请求体：**

[source,json,linenums]
----
{
  "processDefinitionId" : "oneTaskProcess%3A1%3A4"
}
----


All supported JSON parameter fields allowed are exactly the same as the parameters found for <<restHistoricTaskInstancesGet,getting a collection of historic task instances>>, but passed in as JSON-body arguments rather than URL-parameters to allow for more advanced querying and preventing errors with request-uri's that are too long.


.Query for historic activity instances - 响应码
[options="header"]
|===============
|响应码|描述
|200|Indicates request was successful and the activities are returned
|400|Indicates an parameter was passed in the wrong format. 状态描述中包含了额外信息。

|===============


**成功响应体：**

[source,json,linenums]
----
{
  "data": [
    {
      "id" : "5",
      "activityId" : "4",
      "activityName" : "My user task",
      "activityType" : "userTask",
      "processDefinitionId" : "oneTaskProcess%3A1%3A4",
      "processDefinitionUrl" : "http://localhost:8182/repository/process-definitions/oneTaskProcess%3A1%3A4",
      "processInstanceId" : "3",
      "processInstanceUrl" : "http://localhost:8182/history/historic-process-instances/3",
      "executionId" : "4",
      "taskId" : "4",
      "calledProcessInstanceId" : null,
      "assignee" : "fozzie",
      "startTime" : "2013-04-17T10:17:43.902+0000",
      "endTime" : "2013-04-18T14:06:32.715+0000",
      "durationInMillis" : 86400056,
      "tenantId":null
    }
  ],
  "total": 1,
  "start": 0,
  "sort": "name",
  "order": "asc",
  "size": 1
}
----


[[restHistoricVariableInstancesGet]]


==== List of historic variable instances

----
GET history/historic-variable-instances
----

.List of historic variable instances - URL 参数
[options="header"]
|===============
|参数|必填|值|描述
|processInstanceId|否|String|The process instance id of the historic variable instance.
|taskId|否|String|The task id of the historic variable instance.
|excludeTaskVariables|否|Boolean|Indication to exclude the task variables from the result.
|variableName|否|String|The variable name of the historic variable instance.
|variableNameLike|否|String|The variable name using the 'like' operator for the historic variable instance.
|可以在这个URL中使用通用<<restPagingAndSort,分页与排序查询参数>>。

|===============


.List of historic variable instances - 响应码
[options="header"]
|===============
|响应码|描述
|200|Indicates that historic variable instances could be queried.
|400|Indicates an parameter was passed in the wrong format. 状态描述中包含了额外信息。

|===============


**成功响应体：**

[source,json,linenums]
----
{
  "data": [
    {
      "id" : "14",
      "processInstanceId" : "5",
      "processInstanceUrl" : "http://localhost:8182/history/historic-process-instances/5",
      "taskId" : "6",
      "variable" : {
        "name" : "myVariable",
        "variableScope", "global",
        "value" : "test"
      }
    }
  ],
  "total": 1,
  "start": 0,
  "sort": "name",
  "order": "asc",
  "size": 1
}
----



==== Query for historic variable instances

----
POST query/historic-variable-instances
----


**请求体：**

[source,json,linenums]
----
{
  "processDefinitionId" : "oneTaskProcess%3A1%3A4",
  ...

  "variables" : [
    {
      "name" : "myVariable",
      "value" : 1234,
      "operation" : "equals",
      "type" : "long"
    }
  ]
}
----


All supported JSON parameter fields allowed are exactly the same as the parameters found for <<restHistoricVariableInstancesGet,getting a collection of historic process instances>>, but passed in as JSON-body arguments rather than URL-parameters to allow for more advanced querying and preventing errors with request-uri's that are too long. On top of that, the query allows for filtering based on process variables. The +variables+ property is a JSON-array containing objects with the format <<restQueryVariable, as described here.>>

.Query for historic variable instances - 响应码
[options="header"]
|===============
|响应码|描述
|200|Indicates request was successful and the tasks are returned
|400|Indicates an parameter was passed in the wrong format. 状态描述中包含了额外信息。

|===============


**成功响应体：**

[source,json,linenums]
----
{
  "data": [
    {
      "id" : "14",
      "processInstanceId" : "5",
      "processInstanceUrl" : "http://localhost:8182/history/historic-process-instances/5",
      "taskId" : "6",
      "variable" : {
        "name" : "myVariable",
        "variableScope", "global",
        "value" : "test"
      }
    }
  ],
  "total": 1,
  "start": 0,
  "sort": "name",
  "order": "asc",
  "size": 1
}
----


====Get the binary data for a historic task instance variable


----
GET history/historic-variable-instances/{varInstanceId}/data
----

.Get the binary data for a historic task instance variable - 响应码
[options="header"]
|===============
|响应码|描述
|200|Indicates the variable instance was found and the requested variable data is returned.
|404|Indicates the requested variable instance was not found or the variable instance doesn't have a variable with the given name or the variable doesn't have a binary stream available. 状态消息提供了额外信息。

|===============


**成功响应体：**

The response body contains the binary value of the variable. When the variable is of type +binary+, the content-type of the response is set to +application/octet-stream+, regardless of the content of the variable or the request accept-type header. In case of +serializable+, +application/x-java-serialized-object+ is used as content-type.


[[restHistoricDetailGet]]


==== Get historic detail

----
GET history/historic-detail
----

.Get historic detail - URL 参数
[options="header"]
|===============
|参数|必填|值|描述
|id|否|String|The id of the historic detail.
|processInstanceId|否|String|The process instance id of the historic detail.
|executionId|否|String|The execution id of the historic detail.
|activityInstanceId|否|String|The activity instance id of the historic detail.
|taskId|否|String|The task id of the historic detail.
|selectOnlyFormProperties|否|Boolean|Indication to only return form properties in the result.
|selectOnlyVariableUpdates|否|Boolean|Indication to only return variable updates in the result.
|可以在这个URL中使用通用<<restPagingAndSort,分页与排序查询参数>>。

|===============


.Get historic detail - 响应码
[options="header"]
|===============
|响应码|描述
|200|Indicates that historic detail could be queried.
|400|Indicates an parameter was passed in the wrong format. 状态描述中包含了额外信息。

|===============


**成功响应体：**

[source,json,linenums]
----
{
  "data": [
    {
      "id" : "26",
      "processInstanceId" : "5",
      "processInstanceUrl" : "http://localhost:8182/history/historic-process-instances/5",
      "executionId" : "6",
      "activityInstanceId", "10",
      "taskId" : "6",
      "taskUrl" : "http://localhost:8182/history/historic-task-instances/6",
      "time" : "2013-04-17T10:17:43.902+0000",
      "detailType" : "variableUpdate",
      "revision" : 2,
      "variable" : {
        "name" : "myVariable",
        "variableScope", "global",
        "value" : "test"
      },
      "propertyId": null,
      "propertyValue": null
    }
  ],
  "total": 1,
  "start": 0,
  "sort": "name",
  "order": "asc",
  "size": 1
}
----


==== Query for historic details

----
POST query/historic-detail
----

**请求体：**

----
{
  "processInstanceId" : "5",
}
----


All supported JSON parameter fields allowed are exactly the same as the parameters found for <<restHistoricDetailGet,getting a collection of historic process instances>>, but passed in as JSON-body arguments rather than URL-parameters to allow for more advanced querying and preventing errors with request-uri's that are too long.

.Query for historic details - 响应码
[options="header"]
|===============
|响应码|描述
|200|Indicates request was successful and the historic details are returned
|400|Indicates an parameter was passed in the wrong format. 状态描述中包含了额外信息。

|===============


**成功响应体：**

[source,json,linenums]
----
{
  "data": [
    {
      "id" : "26",
      "processInstanceId" : "5",
      "processInstanceUrl" : "http://localhost:8182/history/historic-process-instances/5",
      "executionId" : "6",
      "activityInstanceId", "10",
      "taskId" : "6",
      "taskUrl" : "http://localhost:8182/history/historic-task-instances/6",
      "time" : "2013-04-17T10:17:43.902+0000",
      "detailType" : "variableUpdate",
      "revision" : 2,
      "variable" : {
        "name" : "myVariable",
        "variableScope", "global",
        "value" : "test"
      },
      "propertyId" : null,
      "propertyValue" : null
    }
  ],
  "total": 1,
  "start": 0,
  "sort": "name",
  "order": "asc",
  "size": 1
}
----


==== Get the binary data for a historic detail variable

----
GET history/historic-detail/{detailId}/data
----


.Get the binary data for a historic detail variable - 响应码
[options="header"]
|===============
|响应码|描述
|200|Indicates the historic detail instance was found and the requested variable data is returned.
|404|Indicates the requested historic detail instance was not found or the historic detail instance doesn't have a variable with the given name or the variable doesn't have a binary stream available. 状态消息提供了额外信息。

|===============


**成功响应体：**

The response body contains the binary value of the variable. When the variable is of type +binary+, the content-type of the response is set to +application/octet-stream+, regardless of the content of the variable or the request accept-type header. In case of +serializable+, +application/x-java-serialized-object+ is used as content-type.

=== Forms

==== Get form data

----
GET form/form-data
----

.Get form data - URL 参数
[options="header"]
|===============
|参数|必填|值|描述
|taskId|是 (if no processDefinitionId)|String|The task id corresponding to the form data that needs to be retrieved.
|processDefinitionId|是 (if no taskId)|String|The process definition id corresponding to the start event form data that needs to be retrieved.

|===============


.Get form data - 响应码
[options="header"]
|===============
|响应码|描述
|200|Indicates that form data could be queried.
|404|Indicates that form data could not be found.

|===============


**成功响应体：**

[source,json,linenums]
----
{
  "data": [
    {
      "formKey" : null,
      "deploymentId" : "2",
      "processDefinitionId" : "3",
      "processDefinitionUrl" : "http://localhost:8182/repository/process-definition/3",
      "taskId" : "6",
      "taskUrl" : "http://localhost:8182/runtime/task/6",
      "formProperties" : [
        {
          "id" : "room",
          "name" : "Room",
          "type" : "string",
          "value" : null,
          "readable" : true,
          "writable" : true,
          "required" : true,
          "datePattern" : null,
          "enumValues" : [
            {
              "id" : "normal",
              "name" : "Normal bed"
            },
            {
              "id" : "kingsize",
              "name" : "Kingsize bed"
            },
          ]
        }
      ]
    }
  ],
  "total": 1,
  "start": 0,
  "sort": "name",
  "order": "asc",
  "size": 1
}
----


==== Submit task form data

----
POST form/form-data
----

*Request body for task form:*

[source,json,linenums]
----
{
  "taskId" : "5",
  "properties" : [
    {
      "id" : "room",
      "value" : "normal"
    }
  ]
}
----


*Request body for start event form:*

[source,json,linenums]
----
{
  "processDefinitionId" : "5",
  "businessKey" : "myKey",
  "properties" : [
    {
      "id" : "room",
      "value" : "normal"
    }
  ]
}
----


.Submit task form data - 响应码
[options="header"]
|===============
|响应码|描述
|200|Indicates request was successful and the form data was submitted
|400|Indicates an parameter was passed in the wrong format. 状态描述中包含了额外信息。

|===============


**成功响应体：** for start event form data (no response for task form data):*

[source,json,linenums]
----
{
  "id" : "5",
  "url" : "http://localhost:8182/history/historic-process-instances/5",
  "businessKey" : "myKey",
  "suspended": false,
  "processDefinitionId" : "3",
  "processDefinitionUrl" : "http://localhost:8182/repository/process-definition/3",
  "activityId" : "myTask"
}
----


=== Database tables

==== List of tables

----
GET management/tables
----

.List of tables - 响应码
[options="header"]
|===============
|响应码|描述
|200|Indicates the request was successful.

|===============


**成功响应体：**

[source,json,linenums]
----
[
   {
      "name":"ACT_RU_VARIABLE",
      "url":"http://localhost:8182/management/tables/ACT_RU_VARIABLE",
      "count":4528
   },
   {
      "name":"ACT_RU_EVENT_SUBSCR",
      "url":"http://localhost:8182/management/tables/ACT_RU_EVENT_SUBSCR",
      "count":3
   }

]
----


==== Get a single table

----
GET management/tables/{tableName}
----


.Get a single table - URL 参数
[options="header"]
|===============
|参数|必填|值|描述
|tableName|是|String|The name of the table to get.

|===============


**成功响应体：**

[source,json,linenums]
----
{
      "name":"ACT_RE_PROCDEF",
      "url":"http://localhost:8182/management/tables/ACT_RE_PROCDEF",
      "count":60
}
----


.Get a single table - 响应码
[options="header"]
|===============
|响应码|描述
|200|Indicates the table exists and the table count is returned.
|404|Indicates the requested table does not exist.

|===============




==== Get column info for a single table

----
GET management/tables/{tableName}/columns
----

.Get column info for a single table - URL 参数
[options="header"]
|===============
|参数|必填|值|描述
|tableName|是|String|The name of the table to get.

|===============


**成功响应体：**

[source,json,linenums]
----

{
   "tableName":"ACT_RU_VARIABLE",
   "columnNames":[
      "ID_",
      "REV_",
      "TYPE_",
      "NAME_"


   ],
   "columnTypes":[
      "VARCHAR",
      "INTEGER",
      "VARCHAR",
      "VARCHAR"


   ]
}
----


.Get column info for a single table - 响应码
[options="header"]
|===============
|响应码|描述
|200|Indicates the table exists and the table column info is returned.
|404|Indicates the requested table does not exist.

|===============



==== Get row data for a single table

----
GET management/tables/{tableName}/data
----

.Get row data for a single table - URL 参数
[options="header"]
|===============
|参数|必填|值|描述
|tableName|是|String|The name of the table to get.

|===============


.Get row data for a single table - URL 查询参数
[options="header"]
|===============
|参数|必填|值|描述
|start|否|Integer|Index of the first row to fetch. Defaults to 0.
|size|否|Integer|Number of rows to fetch, starting from +start+. Defaults to 10.
|orderAscendingColumn|否|String|Name of the column to sort the resulting rows on, ascending.
|orderDescendingColumn|否|String|Name of the column to sort the resulting rows on, descending.

|===============


**成功响应体：**

[source,json,linenums]
----
{
  "total":3,
   "start":0,
   "sort":null,
   "order":null,
   "size":3,

   "data":[
      {
         "TASK_ID_":"2",
         "NAME_":"var1",
         "REV_":1,
         "TEXT_":"123",
         "LONG_":123,
         "ID_":"3",
         "TYPE_":"integer"
      }



   ]

}
----

.Get row data for a single table - 响应码
[options="header"]
|===============
|响应码|描述
|200|Indicates the table exists and the table row data is returned.
|404|Indicates the requested table does not exist.

|===============


=== Engine

==== Get engine properties

----
GET management/properties
----


Returns a read-only view of the properties used internally in the engine.

**成功响应体：**

[source,json,linenums]
----
{
   "next.dbid":"101",
   "schema.history":"create(5.15)",
   "schema.version":"5.15"
}
----


.Get engine properties - 响应码
[options="header"]
|===============
|响应码|描述
|200|Indicates the properties are returned.

|===============



==== Get engine info

----
GET management/engine
----


Returns a read-only view of the engine that is used in this REST-service.


**成功响应体：**

[source,json,linenums]
----
{
   "name":"default",
   "version":"5.15",
   "resourceUrl":"file://activiti/activiti.cfg.xml",
   "exception":null
}
----


.Get engine info - 响应码
[options="header"]
|===============
|响应码|描述
|200|Indicates the engine info is returned.

|===============



=== Runtime

==== Signal event received

----
POST runtime/signals
----


Notifies the engine that a signal event has been received, not explicitly related to a specific execution.

**JSON体：**

[source,json,linenums]
----
{
  "signalName": "My Signal",
  "tenantId" : "execute",
  "async": true,
  "variables": [
      {"name": "testVar", "value": "This is a string"}

  ]
}
----


.Signal event received - JSON体参数
[options="header"]
|===============
|参数|描述|必填
|signalName|Name of the signal|是
|tenantId|ID of the tenant that the signal event should be processed in|否
|async|If +true+, handling of the signal will happen asynchronously. Return code will be +202 - Accepted+ to indicate the request is accepted but not yet executed. If +false+,
                    handling the signal will be done immediately and result (++200 - OK++) will only return after this completed successfully. Defaults to ++false++ if omitted.|否
|variables|Array of variables (in the general variables format) to use as payload to pass along with the signal. Cannot be used in case +async+ is set to +true+, this will result in an error.|否

|===============


**成功响应体：**

.Signal event received - 响应码
[options="header"]
|===============
|响应码|描述
|200|Indicated signal has been processed and no errors occurred.
|202|Indicated signal processing is queued as a job, ready to be executed.
|400|Signal not processed. The signal name is missing or variables are used together with async, which is not allowed. Response body contains additional information about the error.

|===============



=== Jobs

==== Get a single job

----
GET management/jobs/{jobId}
----

.Get a single job - URL 参数
[options="header"]
|===============
|参数|必填|值|描述
|jobId|是|String|The id of the job to get.

|===============


**成功响应体：**

[source,json,linenums]
----
{
   "id":"8",
   "url":"http://localhost:8182/management/jobs/8",
   "processInstanceId":"5",
   "processInstanceUrl":"http://localhost:8182/runtime/process-instances/5",
   "processDefinitionId":"timerProcess:1:4",
   "processDefinitionUrl":"http://localhost:8182/repository/process-definitions/timerProcess%3A1%3A4",
   "executionId":"7",
   "executionUrl":"http://localhost:8182/runtime/executions/7",
   "retries":3,
   "exceptionMessage":null,
   "dueDate":"2013-06-04T22:05:05.474+0000",
   "tenantId":null
}
----

.Get a single job - 响应码
[options="header"]
|===============
|响应码|描述
|200|Indicates the job exists and is returned.
|404|Indicates the requested job does not exist.

|===============



==== Delete a job

----
DELETE management/jobs/{jobId}
----


.Delete a job - URL 参数
[options="header"]
|===============
|参数|必填|值|描述
|jobId|是|String|The id of the job to delete.

|===============


.Delete a job - 响应码
[options="header"]
|===============
|响应码|描述
|204|Indicates the job was found and has been deleted. 响应体设置为空。
|404|Indicates the requested job was not found.

|===============



==== Execute a single job

----
POST management/jobs/{jobId}
----


**JSON体：**

[source,json,linenums]
----
{
  "action" : "execute"
}
----


.Execute a single job - JSON体参数
[options="header"]
|===============
|参数|描述|必填
|action|Action to perform. Only +execute+ is supported.|是

|===============


.Execute a single job - 响应码
[options="header"]
|===============
|响应码|描述
|204|Indicates the job was executed. 响应体设置为空。
|404|Indicates the requested job was not found.
|500|Indicates the an exception occurred while executing the job. The status-description contains additional detail about the error. The full error-stacktrace can be fetched later on if needed.

|===============



==== Get the exception stacktrace for a job

----
GET management/jobs/{jobId}/exception-stacktrace
----


.Get the exception stacktrace for a job - URL 参数
[options="header"]
|===============
|参数|描述|必填
|jobId|Id of the job to get the stacktrace for.|是

|===============


.Get the exception stacktrace for a job - 响应码
[options="header"]
|===============
|响应码|描述
|200|Indicates the requested job was not found and the stacktrace has been returned. The response contains the raw stacktrace and always has a Content-type of +text/plain+.
|404|Indicates the requested job was not found or the job doesn't have an exception stacktrace. Status-description contains additional information about the error.

|===============


==== Get a list of jobs


----
GET management/jobs
----


.Get a list of jobs - URL 查询参数
[options="header"]
|===============
|Parameter|Description|Type
|id|Only return job with the given id|String
|processInstanceId|Only return jobs part of a process with the given id|String
|executionId|Only return jobs part of an execution with the given id|String
|processDefinitionId|Only return jobs with the given process definition id|String
|withRetriesLeft|If +true+, only return jobs with retries left. If false, this parameter is ignored.|Boolean
|executable|If +true+, only return jobs which are executable. If false, this parameter is ignored.|Boolean
|timersOnly|If +true+, only return jobs which are timers. If false, this parameter is ignored. Cannot be used together with +$$'messagesOnly'$$+.|Boolean
|messagesOnly|If +true+, only return jobs which are messages. If false, this parameter is ignored. Cannot be used together with +$$'timersOnly'$$+|Boolean
|withException|If +true+, only return jobs for which an exception occurred while executing it. If false, this parameter is ignored.|Boolean
|dueBefore|Only return jobs which are due to be executed before the given date. Jobs without duedate are never returned using this parameter.|Date
|dueAfter|Only return jobs which are due to be executed after the given date. Jobs without duedate are never returned using this parameter.|Date
|exceptionMessage|Only return jobs with the given exception message|String
|tenantId|否|String|Only return jobs with the given tenantId.
|tenantIdLike|否|String|Only return jobs with a tenantId like the given value.
|withoutTenantId|否|Boolean|If +true+, only returns jobs without a tenantId set. 如果值为++false++，则忽略++withoutTenantId++参数。
|sort|Field to sort results on, should be one of +id+, +dueDate+, +executionId+, +processInstanceId+, +retries+ or +tenantId+.|String
|可以在这个URL中使用通用<<restPagingAndSort,分页与排序查询参数>>。

|===============


**成功响应体：**

[source,json,linenums]
----
{
   "data":[
      {
         "id":"13",
         "url":"http://localhost:8182/management/jobs/13",
         "processInstanceId":"5",
         "processInstanceUrl":"http://localhost:8182/runtime/process-instances/5",
         "processDefinitionId":"timerProcess:1:4",
         "processDefinitionUrl":"http://localhost:8182/repository/process-definitions/timerProcess%3A1%3A4",
         "executionId":"12",
         "executionUrl":"http://localhost:8182/runtime/executions/12",
         "retries":0,
         "exceptionMessage":"Can't find scripting engine for 'unexistinglanguage'",
         "dueDate":"2013-06-07T10:00:24.653+0000",
         "tenantId":null
      }



   ],
   "total":2,
   "start":0,
   "sort":"id",
   "order":"asc",
   "size":2
}
----


.Get a list of jobs - 响应码
[options="header"]
|===============
|响应码|描述
|200|Indicates the requested jobs were returned.
|400|Indicates an illegal value has been used in a url query parameter or the both +$$'messagesOnly'$$+ and +$$'timersOnly'$$+ are used as parameters. Status description contains additional details about the error.

|===============



=== Users

==== Get a single user

----
GET identity/users/{userId}
----


.Get a single user - URL 参数
[options="header"]
|===============
|参数|必填|值|描述
|userId|是|String|The id of the user to get.

|===============


**成功响应体：**

[source,json,linenums]
----
{
   "id":"testuser",
   "firstName":"Fred",
   "lastName":"McDonald",
   "url":"http://localhost:8182/identity/users/testuser",
   "email":"no-reply@activiti.org"
}
----


.Get a single user - 响应码
[options="header"]
|===============
|响应码|描述
|200|Indicates the user exists and is returned.
|404|Indicates the requested user does not exist.

|===============



==== Get a list of users


----
GET identity/users
----

.Get a list of users - URL 查询参数
[options="header"]
|===============
|Parameter|Description|Type
|id|Only return user with the given id|String
|firstName|Only return users with the given firstname|String
|lastName|Only return users with the given lastname|String
|email|Only return users with the given email|String
|firstNameLike|Only return userswith a firstname like the given value. Use +%+ as wildcard-character.|String
|lastNameLike|Only return users with a lastname like the given value. Use +%+ as wildcard-character.|String
|emailLike|Only return users with an email like the given value. Use +%+ as wildcard-character.|String
|memberOfGroup|Only return users which are a member of the given group.|String
|potentialStarter|Only return users which are potential starters for a process-definition with the given id.|String
|sort|Field to sort results on, should be one of +id+, +firstName+, +lastname+ or +email+.|String
|可以在这个URL中使用通用<<restPagingAndSort,分页与排序查询参数>>。

|===============


**成功响应体：**

[source,json,linenums]
----
{
   "data":[
      {
         "id":"anotherUser",
         "firstName":"Tijs",
         "lastName":"Barrez",
         "url":"http://localhost:8182/identity/users/anotherUser",
         "email":"no-reply@alfresco.org"
      },
      {
         "id":"kermit",
         "firstName":"Kermit",
         "lastName":"the Frog",
         "url":"http://localhost:8182/identity/users/kermit",
         "email":null
      },
      {
         "id":"testuser",
         "firstName":"Fred",
         "lastName":"McDonald",
         "url":"http://localhost:8182/identity/users/testuser",
         "email":"no-reply@activiti.org"
      }
   ],
   "total":3,
   "start":0,
   "sort":"id",
   "order":"asc",
   "size":3
}
----


.Get a list of users - 响应码
[options="header"]
|===============
|响应码|描述
|200|Indicates the requested users were returned.

|===============



==== Update a user

----
PUT identity/users/{userId}
----

**JSON体：**

[source,json,linenums]
----
{
  "firstName":"Tijs",
  "lastName":"Barrez",
  "email":"no-reply@alfresco.org",
  "password":"pass123"
}
----

All request values are optional. For example, you can only include the 'firstName' attribute in the request body JSON-object, only updating the firstName of the user, leaving all other fields unaffected. When an attribute is explicitly included and is set to null, the user-value will be updated to null. Example: +{"firstName" : null}+ will clear the firstName of the user).


.Update a user - 响应码
[options="header"]
|===============
|响应码|描述
|200|Indicates the user was updated.
|404|Indicates the requested user was not found.
|409|Indicates the requested user was updated simultaneously.

|===============


**成功响应体：** see response for +identity/users/{userId}+.


==== Create a user

----
POST identity/users
----

**JSON体：**

----
{
  "id":"tijs",
  "firstName":"Tijs",
  "lastName":"Barrez",
  "email":"no-reply@alfresco.org",
  "password":"pass123"
}
----

.Create a user - 响应码
[options="header"]
|===============
|响应码|描述
|201|Indicates the user was created.
|400|Indicates the id of the user was missing.

|===============


**成功响应体：** see response for +identity/users/{userId}+.

==== Delete a user

----
DELETE identity/users/{userId}
----

.Delete a user - URL 参数
[options="header"]
|===============
|参数|必填|值|描述
|userId|是|String|The id of the user to delete.

|===============



.Delete a user - 响应码
[options="header"]
|===============
|响应码|描述
|204|Indicates the user was found and  has been deleted. 响应体设置为空。
|404|Indicates the requested user was not found.

|===============


==== Get a user's picture

----
GET identity/users/{userId}/picture
----


.Get a user's picture - URL 参数
[options="header"]
|===============
|参数|必填|值|描述
|userId|是|String|The id of the user to get the picture for.

|===============


**响应体：**

The response body contains the raw picture data, representing the user's picture. The Content-type of the response corresponds to the mimeType that was set when creating the picture.

.Get a user's picture - 响应码
[options="header"]
|===============
|响应码|描述
|200|Indicates the user was found and has a picture, which is returned in the body.
|404|Indicates the requested user was not found or the user does not have a profile picture. Status-description contains additional information about the error.

|===============



==== Updating a user's picture

----
GET identity/users/{userId}/picture
----

.Updating a user's picture - URL 参数
[options="header"]
|===============
|参数|必填|值|描述
|userId|是|String|The id of the user to get the picture for.

|===============


**请求体：**

The request should be of type +multipart/form-data+. There should be a single file-part included with the binary value of the picture. On top of that, the following additional form-fields can be present:

* ++mimeType++: Optional mime-type for the uploaded picture. If omitted, the default of +image/jpeg+ is used as a mime-type for the picture.


.Updating a user's picture - 响应码
[options="header"]
|===============
|响应码|描述
|200|Indicates the user was found and the picture has been updated. The response-body is left empty intentionally.
|404|Indicates the requested user was not found.

|===============



==== List a user's info

----
PUT identity/users/{userId}/info
----


.List a user's info - URL 参数
[options="header"]
|===============
|参数|必填|值|描述
|userId|是|String|The id of the user to get the info for.

|===============



**响应体：**

[source,json,linenums]
----
[
   {
      "key":"key1",
      "url":"http://localhost:8182/identity/users/testuser/info/key1"
   },
   {
      "key":"key2",
      "url":"http://localhost:8182/identity/users/testuser/info/key2"
   }
]
----


.List a user's info - 响应码
[options="header"]
|===============
|响应码|描述
|200|Indicates the user was found and list of info (key and url) is returned.
|404|Indicates the requested user was not found.

|===============




==== Get a user's info

----
GET identity/users/{userId}/info/{key}
----


.Get a user's info - URL 参数
[options="header"]
|===============
|参数|必填|值|描述
|userId|是|String|The id of the user to get the info for.
|key|是|String|The key of the user info to get.

|===============


**响应体：**

[source,json,linenums]
----
{
   "key":"key1",
   "value":"Value 1",
   "url":"http://localhost:8182/identity/users/testuser/info/key1"
}
----


.Get a user's info - 响应码
[options="header"]
|===============
|响应码|描述
|200|Indicates the user was found and the user has info for the given key..
|404|Indicates the requested user was not found or the user doesn't have info for the given key. 状态描述中包含了关于错误的额外信息。

|===============



==== Update a user's info

----
PUT identity/users/{userId}/info/{key}
----

.Update a user's info - URL 参数
[options="header"]
|===============
|参数|必填|值|描述
|userId|是|String|The id of the user to update the info for.
|key|是|String|The key of the user info to update.

|===============


**请求体：**

[source,json,linenums]
----
{
   "value":"The updated value"
}
----

**响应体：**

[source,json,linenums]
----
{
   "key":"key1",
   "value":"The updated value",
   "url":"http://localhost:8182/identity/users/testuser/info/key1"
}
----

.Update a user's info - 响应码
[options="header"]
|===============
|响应码|描述
|200|Indicates the user was found and the info has been updated.
|400|Indicates the value was missing from the request body.
|404|Indicates the requested user was not found or the user doesn't have info for the given key. 状态描述中包含了关于错误的额外信息。

|===============



==== Create a new user's info entry

----
POST identity/users/{userId}/info
----


.Create a new user's info entry - URL 参数
[options="header"]
|===============
|参数|必填|值|描述
|userId|是|String|The id of the user to create the info for.

|===============


**请求体：**

[source,json,linenums]
----
{
   "key":"key1",
   "value":"The value"
}
----


**响应体：**

[source,json,linenums]
----
{
   "key":"key1",
   "value":"The value",
   "url":"http://localhost:8182/identity/users/testuser/info/key1"
}
----


.Create a new user's info entry - 响应码
[options="header"]
|===============
|响应码|描述
|201|Indicates the user was found and the info has been created.
|400|Indicates the key or value was missing from the request body. 状态描述中包含了关于错误的额外信息。
|404|Indicates the requested user was not found.
|409|Indicates there is already an info-entry with the given key for the user, update the resource instance (++PUT++).

|===============



==== Delete a user's info

----
DELETE identity/users/{userId}/info/{key}
----


.Delete a user's info - URL 参数
[options="header"]
|===============
|参数|必填|值|描述
|userId|是|String|The id of the user to delete the info for.
|key|是|String|The key of the user info to delete.

|===============



.Delete a user's info - 响应码
[options="header"]
|===============
|响应码|描述
|204|Indicates the user was found and the info for the given key has been deleted. 响应体设置为空
|404|Indicates the requested user was not found or the user doesn't have info for the given key. 状态描述中包含了关于错误的额外信息。

|===============



=== Groups



==== Get a single group



----
GET identity/groups/{groupId}
----


.Get a single group - URL 参数
[options="header"]
|===============
|参数|必填|值|描述
|groupId|是|String|The id of the group to get.

|===============


**成功响应体：**

[source,json,linenums]
----
{
   "id":"testgroup",
   "url":"http://localhost:8182/identity/groups/testgroup",
   "name":"Test group",
   "type":"Test type"
}
----


.Get a single group - 响应码
[options="header"]
|===============
|响应码|描述
|200|Indicates the group exists and is returned.
|404|Indicates the requested group does not exist.

|===============



==== Get a list of groups


----
GET identity/groups
----


.Get a list of groups - URL 查询参数
[options="header"]
|===============
|Parameter|Description|Type
|id|Only return group with the given id|String
|name|Only return groups with the given name|String
|type|Only return groups with the given type|String
|nameLike|Only return groups with a name like the given value. Use +%+ as wildcard-character.|String
|member|Only return groups which have a member with the given username.|String
|potentialStarter|Only return groups which members are potential starters for a process-definition with the given id.|String
|sort|Field to sort results on, should be one of +id+, +name+ or +type+.|String
|可以在这个URL中使用通用<<restPagingAndSort,分页与排序查询参数>>。

|===============


**成功响应体：**

[source,json,linenums]
----
{
   "data":[
     {
        "id":"testgroup",
        "url":"http://localhost:8182/identity/groups/testgroup",
        "name":"Test group",
        "type":"Test type"
     }
   ],
   "total":3,
   "start":0,
   "sort":"id",
   "order":"asc",
   "size":3
}
----


.Get a list of groups - 响应码
[options="header"]
|===============
|响应码|描述
|200|Indicates the requested groups were returned.

|===============




==== Update a group

----
PUT identity/groups/{groupId}
----

**JSON体：**

[source,json,linenums]
----
{
   "name":"Test group",
   "type":"Test type"
}
----


All request values are optional. For example, you can only include the 'name' attribute in the request body JSON-object, only updating the name of the group, leaving all other fields unaffected. When an attribute is explicitly included and is set to null, the group-value will be updated to null.


.Update a group - 响应码
[options="header"]
|===============
|响应码|描述
|200|Indicates the group was updated.
|404|Indicates the requested group was not found.
|409|Indicates the requested group was updated simultaneously.

|===============


**成功响应体：** see response for +identity/groups/{groupId}+.

==== Create a group

----
POST identity/groups
----

**JSON体：**

[source,json,linenums]
----
{
   "id":"testgroup",
   "name":"Test group",
   "type":"Test type"
}
----


.Create a group - 响应码
[options="header"]
|===============
|响应码|描述
|201|Indicates the group was created.
|400|Indicates the id of the group was missing.

|===============

**成功响应体：** see response for +identity/groups/{groupId}+.


==== Delete a group

----
DELETE identity/groups/{groupId}
----


.Delete a group - URL 参数
[options="header"]
|===============
|参数|必填|值|描述
|groupId|是|String|The id of the group to delete.

|===============


.Delete a group - 响应码
[options="header"]
|===============
|响应码|描述
|204|Indicates the group was found and  has been deleted. 响应体设置为空。
|404|Indicates the requested group was not found.

|===============



==== Get members in a group

There is no GET allowed on +identity/groups/members+. Use the +identity/users?memberOfGroup=sales+ URL to get all users that are part of a particular group.



==== Add a member to a group



----
POST identity/groups/{groupId}/members
----


.Add a member to a group - URL 参数
[options="header"]
|===============
|参数|必填|值|描述
|groupId|是|String|The id of the group to add a member to.

|===============



**JSON体：**

[source,json,linenums]
----
{
   "userId":"kermit"
}
----


.Add a member to a group - 响应码
[options="header"]
|===============
|响应码|描述
|201|Indicates the group was found and the member has been added.
|404|Indicates the userId was not included in the request body.
|404|Indicates the requested group was not found.
|409|Indicates the requested user is already a member of the group.

|===============


**响应体：**

[source,json,linenums]
----
{
   "userId":"kermit",
   "groupId":"sales",
    "url":"http://localhost:8182/identity/groups/sales/members/kermit"
}
----


==== Delete a member from a group


----
DELETE identity/groups/{groupId}/members/{userId}
----

.Delete a member from a group - URL 参数
[options="header"]
|===============
|参数|必填|值|描述
|groupId|是|String|The id of the group to remove a member from.
|userId|是|String|The id of the user to remove.

|===============



.Delete a member from a group - 响应码
[options="header"]
|===============
|响应码|描述
|204|Indicates the group was found and the member has been deleted. The 响应体设置为空
|404|Indicates the requested group was not found or that the user is not a member of the group. The 状态描述中包含了关于错误的额外信息。

|===============


**响应体：**

[source,json,linenums]
----
{
   "userId":"kermit",
   "groupId":"sales",
    "url":"http://localhost:8182/identity/groups/sales/members/kermit"
}
----




